package util;

public class Jsons {

	public static final String VIRTUAL_SERVER = "{\n" + "  \"virtual-server\": {\n" + "    \"port-list\": [\n"
			+ "      {\n" + "        \"ha-conn-mirror\": 0,\n" + "        \"protocol\": \"string\",\n"
			+ "        \"precedence\": 0,\n" + "        \"port-translation\": 0,\n"
			+ "        \"ip-map-list\": \"string\",\n" + "        \"template-reqmod-icap\": \"string\",\n"
			+ "        \"acl-name-list\": [\n" + "          {\n"
			+ "            \"acl-name-src-nat-pool-shared\": \"string\",\n"
			+ "            \"shared-partition-pool-name\": 0,\n" + "            \"acl-name-seq-num-shared\": 0,\n"
			+ "            \"acl-name\": \"string\",\n" + "            \"acl-name-src-nat-pool\": \"string\",\n"
			+ "            \"acl-name-seq-num\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"stats-data-action\": \"string\",\n" + "        \"use-default-if-no-server\": 0,\n"
			+ "        \"template-connection-reuse\": \"string\",\n" + "        \"uuid\": \"string\",\n"
			+ "        \"template-tcp-shared\": \"string\",\n" + "        \"template-tcp\": \"string\",\n"
			+ "        \"template-persist-cookie\": \"string\",\n"
			+ "        \"shared-partition-dynamic-service-template\": 0,\n"
			+ "        \"shared-partition-connection-reuse-template\": 0,\n" + "        \"when-down\": 0,\n"
			+ "        \"template-client-ssl-shared\": \"string\",\n"
			+ "        \"shared-partition-persist-destination-ip-template\": 0,\n"
			+ "        \"shared-partition-external-service-template\": 0,\n" + "        \"persist-type\": \"string\",\n"
			+ "        \"shared-partition-http-policy-template\": 0,\n" + "        \"use-rcv-hop-for-resp\": 0,\n"
			+ "        \"scaleout-bucket-count\": 0,\n" + "        \"optimization-level\": \"string\",\n"
			+ "        \"req-fail\": 0,\n" + "        \"no-dest-nat\": 0,\n" + "        \"name\": \"string\",\n"
			+ "        \"template-smpp\": \"string\",\n" + "        \"user-tag\": \"string\",\n"
			+ "        \"template-diameter\": \"string\",\n" + "        \"sampling-enable\": [\n" + "          {\n"
			+ "            \"counters1\": \"string\"\n" + "          }\n" + "        ],\n"
			+ "        \"template-ssli\": \"string\",\n" + "        \"shared-partition-persist-cookie-template\": 0,\n"
			+ "        \"shared-partition-policy-template\": 0,\n" + "        \"template-policy\": \"string\",\n"
			+ "        \"no-logging\": 0,\n" + "        \"reset-on-server-selection-fail\": 0,\n"
			+ "        \"waf-template\": \"string\",\n" + "        \"ipinip\": 0,\n"
			+ "        \"no-auto-up-on-aflex\": 0,\n" + "        \"rate\": 0,\n" + "        \"gslb-enable\": 0,\n"
			+ "        \"template-dns-shared\": \"string\",\n" + "        \"template-persist-ssl-sid\": \"string\",\n"
			+ "        \"template-dns\": \"string\",\n" + "        \"shared-partition-dns-template\": 0,\n"
			+ "        \"template-sip\": \"string\",\n" + "        \"template-dblb\": \"string\",\n"
			+ "        \"shared-partition-server-ssl-template\": 0,\n"
			+ "        \"template-client-ssl\": \"string\",\n" + "        \"support-http2\": 0,\n"
			+ "        \"template-client-ssh\": \"string\",\n" + "        \"shared-partition-tcp-proxy-template\": 0,\n"
			+ "        \"enable-playerid-check\": 0,\n" + "        \"service-group\": \"string\",\n"
			+ "        \"shared-partition-persist-ssl-sid-template\": 0,\n"
			+ "        \"def-selection-if-pref-failed\": \"string\",\n" + "        \"shared-partition-udp\": 0,\n"
			+ "        \"syn-cookie\": 0,\n" + "        \"alternate-port\": 0,\n"
			+ "        \"alternate-port-number\": 0,\n" + "        \"template-persist-source-ip-shared\": \"string\",\n"
			+ "        \"template-cache\": \"string\",\n" + "        \"template-persist-cookie-shared\": \"string\",\n"
			+ "        \"rtp-sip-call-id-match\": 0,\n" + "        \"template-file-inspection\": \"string\",\n"
			+ "        \"template-ftp\": \"string\",\n" + "        \"serv-sel-fail\": 0,\n"
			+ "        \"template-udp\": \"string\",\n" + "        \"template-virtual-port-shared\": \"string\",\n"
			+ "        \"action\": \"string\",\n" + "        \"template-http\": \"string\",\n"
			+ "        \"view\": 0,\n" + "        \"template-persist-source-ip\": \"string\",\n"
			+ "        \"template-dynamic-service\": \"string\",\n"
			+ "        \"shared-partition-virtual-port-template\": 0,\n" + "        \"use-cgnv6\": 0,\n"
			+ "        \"template-persist-destination-ip\": \"string\",\n"
			+ "        \"template-virtual-port\": \"string\",\n" + "        \"conn-limit\": 0,\n"
			+ "        \"trunk-fwd\": 0,\n" + "        \"template-udp-shared\": \"string\",\n"
			+ "        \"template-http-policy-shared\": \"string\",\n" + "        \"pool\": \"string\",\n"
			+ "        \"snat-on-vip\": 0,\n" + "        \"template-connection-reuse-shared\": \"string\",\n"
			+ "        \"shared-partition-tcp\": 0,\n" + "        \"acl-id-list\": [\n" + "          {\n"
			+ "            \"acl-id-seq-num\": 0,\n" + "            \"acl-id-src-nat-pool\": \"string\",\n"
			+ "            \"acl-id-seq-num-shared\": 0,\n" + "            \"acl-id\": 0,\n"
			+ "            \"shared-partition-pool-id\": 0,\n"
			+ "            \"acl-id-src-nat-pool-shared\": \"string\"\n" + "          }\n" + "        ],\n"
			+ "        \"shared-partition-http-template\": 0,\n"
			+ "        \"template-external-service\": \"string\",\n" + "        \"on-syn\": 0,\n"
			+ "        \"template-persist-ssl-sid-shared\": \"string\",\n" + "        \"force-routing-mode\": 0,\n"
			+ "        \"template-http-policy\": \"string\",\n" + "        \"template-policy-shared\": \"string\",\n"
			+ "        \"template-scaleout\": \"string\",\n" + "        \"when-down-protocol2\": 0,\n"
			+ "        \"template-fix\": \"string\",\n" + "        \"template-smtp\": \"string\",\n"
			+ "        \"redirect-to-https\": 0,\n" + "        \"alt-protocol2\": \"string\",\n"
			+ "        \"alt-protocol1\": \"string\",\n" + "        \"message-switching\": 0,\n"
			+ "        \"template-imap-pop3\": \"string\",\n" + "        \"scaleout-device-group\": 0,\n"
			+ "        \"shared-partition-persist-source-ip-template\": 0,\n" + "        \"l7-hardware-assist\": 0,\n"
			+ "        \"template-tcp-proxy-shared\": \"string\",\n"
			+ "        \"shared-partition-cache-template\": 0,\n" + "        \"use-alternate-port\": 0,\n"
			+ "        \"template-tcp-proxy-server\": \"string\",\n" + "        \"trunk-rev\": 0,\n"
			+ "        \"eth-fwd\": 0,\n" + "        \"pool-shared\": \"string\",\n"
			+ "        \"template-respmod-icap\": \"string\",\n" + "        \"range\": 0,\n" + "        \"reset\": 0,\n"
			+ "        \"template-external-service-shared\": \"string\",\n" + "        \"auto\": 0,\n"
			+ "        \"template-dynamic-service-shared\": \"string\",\n"
			+ "        \"template-server-ssh\": \"string\",\n" + "        \"aflex-scripts\": [\n" + "          {\n"
			+ "            \"aflex\": \"string\",\n" + "            \"aflex-shared\": \"string\"\n" + "          }\n"
			+ "        ],\n" + "        \"template-http-shared\": \"string\",\n"
			+ "        \"template-server-ssl\": \"string\",\n" + "        \"shared-partition-diameter-template\": 0,\n"
			+ "        \"template-server-ssl-shared\": \"string\",\n"
			+ "        \"template-persist-destination-ip-shared\": \"string\",\n"
			+ "        \"template-cache-shared\": \"string\",\n" + "        \"port-number\": 0,\n"
			+ "        \"template-tcp-proxy-client\": \"string\",\n" + "        \"shared-partition-pool\": 0,\n"
			+ "        \"template-tcp-proxy\": \"string\",\n" + "        \"extended-stats\": 0,\n"
			+ "        \"shared-partition-client-ssl-template\": 0,\n" + "        \"expand\": 0,\n"
			+ "        \"skip-rev-hash\": 0,\n" + "        \"template-diameter-shared\": \"string\",\n"
			+ "        \"clientip-sticky-nat\": 0,\n" + "        \"secs\": 0,\n" + "        \"auth-cfg\": {\n"
			+ "          \"aaa-policy\": \"string\"\n" + "        },\n" + "        \"eth-rev\": 0\n" + "      }\n"
			+ "    ],\n" + "    \"stats-data-action\": \"string\",\n" + "    \"ipv6-acl-shared\": \"string\",\n"
			+ "    \"acl-name\": \"string\",\n" + "    \"enable-disable-action\": \"string\",\n"
			+ "    \"ha-dynamic\": 0,\n" + "    \"redistribute-route-map\": \"string\",\n"
			+ "    \"acl-name-shared\": \"string\",\n" + "    \"ip-address\": \"string\",\n"
			+ "    \"migrate-vip\": {\n" + "      \"target-data-cpu\": 0,\n" + "      \"uuid\": \"string\",\n"
			+ "      \"finish-migration\": 0,\n" + "      \"target-floating-ipv6\": \"string\",\n"
			+ "      \"target-floating-ipv4\": \"string\",\n" + "      \"cancel-migration\": 0\n" + "    },\n"
			+ "    \"use-if-ip\": 0,\n" + "    \"uuid\": \"string\",\n" + "    \"vrid\": 0,\n"
			+ "    \"disable-vip-adv\": 0,\n" + "    \"template-virtual-server\": \"string\",\n"
			+ "    \"arp-disable\": 0,\n" + "    \"description\": \"string\",\n"
			+ "    \"redistribution-flagged\": 0,\n" + "    \"netmask\": \"string\",\n" + "    \"acl-id\": 0,\n"
			+ "    \"ipv6-acl\": \"string\",\n" + "    \"template-logging\": \"string\",\n"
			+ "    \"extended-stats\": 0,\n" + "    \"name\": \"string\",\n"
			+ "    \"template-scaleout\": \"string\",\n" + "    \"template-policy\": \"string\",\n"
			+ "    \"user-tag\": \"string\",\n" + "    \"template-policy-shared\": \"string\",\n"
			+ "    \"ipv6-address\": \"string\",\n" + "    \"ethernet\": 0,\n"
			+ "    \"shared-partition-policy-template\": 0,\n" + "    \"acl-id-shared\": 0\n" + "  }\n" + "}";

	public static final String SERVICE_GROUP = "{\n" + "  \"service-group\": {\n" + "    \"conn-rate\": 0,\n"
			+ "    \"reset-on-server-selection-fail\": 0,\n" + "    \"health-check-disable\": 0,\n"
			+ "    \"protocol\": \"string\",\n" + "    \"traffic-replication-mirror-ip-repl\": 0,\n"
			+ "    \"reset-priority-affinity\": 0,\n" + "    \"priorities\": [\n" + "      {\n"
			+ "        \"priority\": 0,\n" + "        \"priority-action\": \"string\"\n" + "      }\n" + "    ],\n"
			+ "    \"min-active-member\": 0,\n" + "    \"member-list\": [\n" + "      {\n"
			+ "        \"member-priority\": 0,\n" + "        \"uuid\": \"string\",\n"
			+ "        \"fqdn-name\": \"string\",\n" + "        \"resolve-as\": \"string\",\n"
			+ "        \"sampling-enable\": [\n" + "          {\n" + "            \"counters1\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"member-template\": \"string\",\n"
			+ "        \"name\": \"string\",\n" + "        \"host\": \"string\",\n"
			+ "        \"user-tag\": \"string\",\n" + "        \"member-state\": \"string\",\n"
			+ "        \"server-ipv6-addr\": \"string\",\n" + "        \"port\": 0,\n"
			+ "        \"member-stats-data-disable\": 0\n" + "      }\n" + "    ],\n"
			+ "    \"stats-data-action\": \"string\",\n" + "    \"traffic-replication-mirror-da-repl\": 0,\n"
			+ "    \"template-policy-shared\": \"string\",\n" + "    \"rpt-ext-server\": 0,\n"
			+ "    \"template-port\": \"string\",\n" + "    \"conn-rate-grace-period\": 0,\n"
			+ "    \"l4-session-usage-duration\": 0,\n" + "    \"uuid\": \"string\",\n"
			+ "    \"backup-server-event-log\": 0,\n" + "    \"lc-method\": \"string\",\n"
			+ "    \"pseudo-round-robin\": 0,\n" + "    \"shared-partition-policy-template\": 0,\n"
			+ "    \"l4-session-usage-revert-rate\": 0,\n" + "    \"shared-partition-svcgrp-health-check\": 0,\n"
			+ "    \"template-server\": \"string\",\n" + "    \"svcgrp-health-check-shared\": \"string\",\n"
			+ "    \"traffic-replication-mirror\": 0,\n" + "    \"l4-session-revert-duration\": 0,\n"
			+ "    \"traffic-replication-mirror-sa-da-repl\": 0,\n" + "    \"lb-method\": \"string\",\n"
			+ "    \"stateless-auto-switch\": 0,\n" + "    \"min-active-member-action\": \"string\",\n"
			+ "    \"l4-session-usage\": 0,\n" + "    \"extended-stats\": 0,\n"
			+ "    \"conn-rate-revert-duration\": 0,\n" + "    \"strict-select\": 0,\n" + "    \"name\": \"string\",\n"
			+ "    \"reset\": {\n" + "      \"auto-switch\": 0\n" + "    },\n"
			+ "    \"traffic-replication-mirror-sa-repl\": 0,\n" + "    \"report-delay\": 0,\n"
			+ "    \"conn-rate-log\": 0,\n" + "    \"l4-session-usage-log\": 0,\n" + "    \"conn-rate-duration\": 0,\n"
			+ "    \"stateless-lb-method\": \"string\",\n" + "    \"template-policy\": \"string\",\n"
			+ "    \"stateless-lb-method2\": \"string\",\n" + "    \"user-tag\": \"string\",\n"
			+ "    \"sample-rsp-time\": 0,\n" + "    \"sampling-enable\": [\n" + "      {\n"
			+ "        \"counters1\": \"string\"\n" + "      }\n" + "    ],\n" + "    \"top-fastest\": 0,\n"
			+ "    \"conn-revert-rate\": 0,\n" + "    \"l4-session-usage-grace-period\": 0,\n"
			+ "    \"priority-affinity\": 0,\n" + "    \"top-slowest\": 0,\n" + "    \"health-check\": \"string\"\n"
			+ "  }\n" + "}";

	public static final String SERVERS = "{\n" + "  \"server\": {\n" + "    \"health-check-disable\": 0,\n"
			+ "    \"port-list\": [\n" + "      {\n" + "        \"health-check-disable\": 0,\n"
			+ "        \"protocol\": \"string\",\n" + "        \"weight\": 0,\n"
			+ "        \"shared-rport-health-check\": 0,\n" + "        \"stats-data-action\": \"string\",\n"
			+ "        \"health-check-follow-port\": 0,\n" + "        \"template-port\": \"string\",\n"
			+ "        \"conn-limit\": 0,\n" + "        \"uuid\": \"string\",\n" + "        \"support-http2\": 0,\n"
			+ "        \"sampling-enable\": [\n" + "          {\n" + "            \"counters1\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"no-ssl\": 0,\n"
			+ "        \"follow-port-protocol\": \"string\",\n" + "        \"template-server-ssl\": \"string\",\n"
			+ "        \"alternate-port\": [\n" + "          {\n" + "            \"alternate-name\": \"string\",\n"
			+ "            \"alternate\": 0,\n" + "            \"alternate-server-port\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"port-number\": 0,\n" + "        \"extended-stats\": 0,\n"
			+ "        \"rport-health-check-shared\": \"string\",\n" + "        \"conn-resume\": 0,\n"
			+ "        \"user-tag\": \"string\",\n" + "        \"range\": 0,\n" + "        \"auth-cfg\": {\n"
			+ "          \"service-principal-name\": \"string\"\n" + "        },\n"
			+ "        \"action\": \"string\",\n" + "        \"health-check\": \"string\",\n"
			+ "        \"no-logging\": 0\n" + "      }\n" + "    ],\n" + "    \"stats-data-action\": \"string\",\n"
			+ "    \"slow-start\": 0,\n" + "    \"weight\": 0,\n" + "    \"spoofing-cache\": 0,\n"
			+ "    \"resolve-as\": \"string\",\n" + "    \"conn-limit\": 0,\n" + "    \"uuid\": \"string\",\n"
			+ "    \"fqdn-name\": \"string\",\n" + "    \"external-ip\": \"string\",\n"
			+ "    \"health-check-shared\": \"string\",\n" + "    \"ipv6\": \"string\",\n"
			+ "    \"template-server\": \"string\",\n" + "    \"server-ipv6-addr\": \"string\",\n"
			+ "    \"alternate-server\": [\n" + "      {\n" + "        \"alternate-name\": \"string\",\n"
			+ "        \"alternate\": 0\n" + "      }\n" + "    ],\n" + "    \"shared-partition-health-check\": 0,\n"
			+ "    \"host\": \"string\",\n" + "    \"extended-stats\": 0,\n" + "    \"conn-resume\": 0,\n"
			+ "    \"name\": \"string\",\n" + "    \"user-tag\": \"string\",\n" + "    \"sampling-enable\": [\n"
			+ "      {\n" + "        \"counters1\": \"string\"\n" + "      }\n" + "    ],\n"
			+ "    \"action\": \"string\",\n" + "    \"health-check\": \"string\",\n" + "    \"no-logging\": 0\n"
			+ "  }\n" + "}";

	public static final String IP = "{\n" + "  \"ip\": {\n" + "    \"uuid\": \"string\",\n"
			+ "    \"address-list\": [\n" + "      {\n" + "        \"ipv4-address\": \"string\",\n"
			+ "        \"ipv4-netmask\": \"string\"\n" + "      }\n" + "    ],\n"
			+ "    \"generate-membership-query\": 0,\n" + "    \"cache-spoofing-port\": 0,\n" + "    \"inside\": 0,\n"
			+ "    \"allow-promiscuous-vip\": 0,\n" + "    \"client\": 0,\n" + "    \"max-resp-time\": 0,\n"
			+ "    \"query-interval\": 0,\n" + "    \"outside\": 0,\n" + "    \"helper-address-list\": [\n"
			+ "      {\n" + "        \"helper-address\": \"string\"\n" + "      }\n" + "    ],\n"
			+ "    \"stateful-firewall\": {\n" + "      \"uuid\": \"string\",\n" + "      \"class-list\": \"string\",\n"
			+ "      \"inside\": 0,\n" + "      \"outside\": 0,\n" + "      \"acl-id\": 0,\n"
			+ "      \"access-list\": 0\n" + "    },\n" + "    \"rip\": {\n" + "      \"receive-cfg\": {\n"
			+ "        \"receive\": 0,\n" + "        \"version\": \"string\"\n" + "      },\n"
			+ "      \"uuid\": \"string\",\n" + "      \"receive-packet\": 0,\n" + "      \"split-horizon-cfg\": {\n"
			+ "        \"state\": \"string\"\n" + "      },\n" + "      \"authentication\": {\n"
			+ "        \"key-chain\": {\n" + "          \"key-chain\": \"string\"\n" + "        },\n"
			+ "        \"mode\": {\n" + "          \"mode\": \"string\"\n" + "        },\n" + "        \"str\": {\n"
			+ "          \"string\": \"string\"\n" + "        }\n" + "      },\n" + "      \"send-cfg\": {\n"
			+ "        \"version\": \"string\",\n" + "        \"send\": 0\n" + "      },\n"
			+ "      \"send-packet\": 0\n" + "    },\n" + "    \"ttl-ignore\": 0,\n" + "    \"router\": {\n"
			+ "      \"isis\": {\n" + "        \"tag\": \"string\",\n" + "        \"uuid\": \"string\"\n" + "      }\n"
			+ "    },\n" + "    \"dhcp\": 0,\n" + "    \"server\": 0,\n" + "    \"ospf\": {\n"
			+ "      \"ospf-ip-list\": [\n" + "        {\n" + "          \"dead-interval\": 0,\n"
			+ "          \"authentication-key\": \"string\",\n" + "          \"uuid\": \"string\",\n"
			+ "          \"mtu-ignore\": 0,\n" + "          \"transmit-delay\": 0,\n"
			+ "          \"value\": \"string\",\n" + "          \"priority\": 0,\n"
			+ "          \"authentication\": 0,\n" + "          \"cost\": 0,\n"
			+ "          \"database-filter\": \"string\",\n" + "          \"hello-interval\": 0,\n"
			+ "          \"ip-addr\": \"string\",\n" + "          \"retransmit-interval\": 0,\n"
			+ "          \"message-digest-cfg\": [\n" + "            {\n" + "              \"message-digest-key\": 0,\n"
			+ "              \"md5\": {\n" + "                \"md5-value\": \"string\",\n"
			+ "                \"encrypted\": \"Unknown Type: encrypted\"\n" + "              }\n" + "            }\n"
			+ "          ],\n" + "          \"out\": 0\n" + "        }\n" + "      ],\n" + "      \"ospf-global\": {\n"
			+ "        \"cost\": 0,\n" + "        \"dead-interval\": 0,\n"
			+ "        \"authentication-key\": \"string\",\n" + "        \"network\": {\n"
			+ "          \"broadcast\": 0,\n" + "          \"point-to-multipoint\": 0,\n"
			+ "          \"non-broadcast\": 0,\n" + "          \"point-to-point\": 0,\n"
			+ "          \"p2mp-nbma\": 0\n" + "        },\n" + "        \"mtu-ignore\": 0,\n"
			+ "        \"transmit-delay\": 0,\n" + "        \"authentication-cfg\": {\n"
			+ "          \"authentication\": 0,\n" + "          \"value\": \"string\"\n" + "        },\n"
			+ "        \"retransmit-interval\": 0,\n" + "        \"bfd-cfg\": {\n" + "          \"disable\": 0,\n"
			+ "          \"bfd\": 0\n" + "        },\n" + "        \"disable\": \"string\",\n"
			+ "        \"hello-interval\": 0,\n" + "        \"database-filter-cfg\": {\n"
			+ "          \"database-filter\": \"string\",\n" + "          \"out\": 0\n" + "        },\n"
			+ "        \"priority\": 0,\n" + "        \"mtu\": 0,\n" + "        \"message-digest-cfg\": [\n"
			+ "          {\n" + "            \"message-digest-key\": 0,\n" + "            \"md5\": {\n"
			+ "              \"md5-value\": \"string\",\n"
			+ "              \"encrypted\": \"Unknown Type: encrypted\"\n" + "            }\n" + "          }\n"
			+ "        ],\n" + "        \"uuid\": \"string\"\n" + "      }\n" + "    },\n"
			+ "    \"slb-partition-redirect\": 0\n" + "  }\n" + "}";

	public static final String ETHERNET = "{\n" + "  \"ethernet\": {\n" + "    \"fec-forced-on\": 0,\n"
			+ "    \"trap-source\": 0,\n" + "    \"ip\": {\n" + "      \"uuid\": \"string\",\n"
			+ "      \"address-list\": [\n" + "        {\n" + "          \"address-type\": \"string\",\n"
			+ "          \"ipv6-addr\": \"string\"\n" + "        }\n" + "      ],\n"
			+ "      \"generate-membership-query\": 0,\n" + "      \"cache-spoofing-port\": 0,\n"
			+ "      \"inside\": 0,\n" + "      \"allow-promiscuous-vip\": 0,\n" + "      \"client\": 0,\n"
			+ "      \"max-resp-time\": 0,\n" + "      \"query-interval\": 0,\n" + "      \"outside\": 0,\n"
			+ "      \"helper-address-list\": [\n" + "        {\n" + "          \"helper-address\": \"string\"\n"
			+ "        }\n" + "      ],\n" + "      \"stateful-firewall\": {\n" + "        \"uuid\": \"string\",\n"
			+ "        \"class-list\": \"string\",\n" + "        \"inside\": 0,\n" + "        \"outside\": 0,\n"
			+ "        \"acl-id\": 0,\n" + "        \"access-list\": 0\n" + "      },\n" + "      \"rip\": {\n"
			+ "        \"receive-cfg\": {\n" + "          \"receive\": 0,\n" + "          \"version\": \"string\"\n"
			+ "        },\n" + "        \"uuid\": \"string\",\n" + "        \"receive-packet\": 0,\n"
			+ "        \"split-horizon-cfg\": {\n" + "          \"state\": \"string\"\n" + "        },\n"
			+ "        \"authentication\": {\n" + "          \"key-chain\": {\n"
			+ "            \"key-chain\": \"string\"\n" + "          },\n" + "          \"mode\": {\n"
			+ "            \"mode\": \"string\"\n" + "          },\n" + "          \"str\": {\n"
			+ "            \"string\": \"string\"\n" + "          }\n" + "        },\n" + "        \"send-cfg\": {\n"
			+ "          \"version\": \"string\",\n" + "          \"send\": 0\n" + "        },\n"
			+ "        \"send-packet\": 0\n" + "      },\n" + "      \"ttl-ignore\": 0,\n" + "      \"router\": {\n"
			+ "        \"isis\": {\n" + "          \"tag\": \"string\",\n" + "          \"uuid\": \"string\"\n"
			+ "        }\n" + "      },\n" + "      \"dhcp\": 0,\n" + "      \"server\": 0,\n" + "      \"ospf\": {\n"
			+ "        \"ospf-ip-list\": [\n" + "          {\n" + "            \"dead-interval\": 0,\n"
			+ "            \"authentication-key\": \"string\",\n" + "            \"uuid\": \"string\",\n"
			+ "            \"mtu-ignore\": 0,\n" + "            \"transmit-delay\": 0,\n"
			+ "            \"value\": \"string\",\n" + "            \"priority\": 0,\n"
			+ "            \"authentication\": 0,\n" + "            \"cost\": 0,\n"
			+ "            \"database-filter\": \"string\",\n" + "            \"hello-interval\": 0,\n"
			+ "            \"ip-addr\": \"string\",\n" + "            \"retransmit-interval\": 0,\n"
			+ "            \"message-digest-cfg\": [\n" + "              {\n"
			+ "                \"message-digest-key\": 0,\n" + "                \"md5\": {\n"
			+ "                  \"md5-value\": \"string\",\n"
			+ "                  \"encrypted\": \"Unknown Type: encrypted\"\n" + "                }\n"
			+ "              }\n" + "            ],\n" + "            \"out\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"ospf-global\": {\n" + "          \"cost\": 0,\n" + "          \"dead-interval\": 0,\n"
			+ "          \"authentication-key\": \"string\",\n" + "          \"network\": {\n"
			+ "            \"broadcast\": 0,\n" + "            \"point-to-multipoint\": 0,\n"
			+ "            \"non-broadcast\": 0,\n" + "            \"point-to-point\": 0,\n"
			+ "            \"p2mp-nbma\": 0\n" + "          },\n" + "          \"mtu-ignore\": 0,\n"
			+ "          \"transmit-delay\": 0,\n" + "          \"authentication-cfg\": {\n"
			+ "            \"authentication\": 0,\n" + "            \"value\": \"string\"\n" + "          },\n"
			+ "          \"retransmit-interval\": 0,\n" + "          \"bfd-cfg\": {\n" + "            \"disable\": 0,\n"
			+ "            \"bfd\": 0\n" + "          },\n" + "          \"disable\": \"string\",\n"
			+ "          \"hello-interval\": 0,\n" + "          \"database-filter-cfg\": {\n"
			+ "            \"database-filter\": \"string\",\n" + "            \"out\": 0\n" + "          },\n"
			+ "          \"priority\": 0,\n" + "          \"mtu\": 0,\n" + "          \"message-digest-cfg\": [\n"
			+ "            {\n" + "              \"message-digest-key\": 0,\n" + "              \"md5\": {\n"
			+ "                \"md5-value\": \"string\",\n"
			+ "                \"encrypted\": \"Unknown Type: encrypted\"\n" + "              }\n" + "            }\n"
			+ "          ],\n" + "          \"uuid\": \"string\"\n" + "        }\n" + "      },\n"
			+ "      \"slb-partition-redirect\": 0\n" + "    },\n" + "    \"ddos\": {\n" + "      \"outside\": 0,\n"
			+ "      \"inside\": 0,\n" + "      \"uuid\": \"string\"\n" + "    },\n"
			+ "    \"l3-vlan-fwd-disable\": 0,\n" + "    \"access-list\": {\n" + "      \"acl-name\": \"string\",\n"
			+ "      \"acl-id\": 0\n" + "    },\n" + "    \"speed\": \"string\",\n" + "    \"speed-forced-40g\": 0,\n"
			+ "    \"lldp\": {\n" + "      \"tx-dot1-cfg\": {\n" + "        \"link-aggregation\": 0,\n"
			+ "        \"vlan\": 0,\n" + "        \"tx-dot1-tlvs\": 0\n" + "      },\n"
			+ "      \"notification-cfg\": {\n" + "        \"notification\": 0,\n" + "        \"notif-enable\": 0\n"
			+ "      },\n" + "      \"enable-cfg\": {\n" + "        \"rx\": 0,\n" + "        \"tx\": 0,\n"
			+ "        \"rt-enable\": 0\n" + "      },\n" + "      \"tx-tlvs-cfg\": {\n"
			+ "        \"system-capabilities\": 0,\n" + "        \"system-description\": 0,\n"
			+ "        \"management-address\": 0,\n" + "        \"tx-tlvs\": 0,\n" + "        \"exclude\": 0,\n"
			+ "        \"port-description\": 0,\n" + "        \"system-name\": 0\n" + "      },\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"uuid\": \"string\",\n" + "    \"bfd\": {\n"
			+ "      \"interval-cfg\": {\n" + "        \"interval\": 0,\n" + "        \"min-rx\": 0,\n"
			+ "        \"multiplier\": 0\n" + "      },\n" + "      \"authentication\": {\n"
			+ "        \"encrypted\": \"Unknown Type: encrypted\",\n" + "        \"password\": \"string\",\n"
			+ "        \"method\": \"string\",\n" + "        \"key-id\": 0\n" + "      },\n" + "      \"echo\": 0,\n"
			+ "      \"uuid\": \"string\",\n" + "      \"demand\": 0\n" + "    },\n" + "    \"media-type-copper\": 0,\n"
			+ "    \"ifnum\": 0,\n" + "    \"remove-vlan-tag\": 0,\n" + "    \"monitor-list\": [\n" + "      {\n"
			+ "        \"monitor-vlan\": 0,\n" + "        \"monitor\": \"string\",\n" + "        \"mirror-index\": 0\n"
			+ "      }\n" + "    ],\n" + "    \"cpu-process\": 0,\n" + "    \"auto-neg-enable\": 0,\n"
			+ "    \"map\": {\n" + "      \"inside\": 0,\n" + "      \"map-t-inside\": 0,\n"
			+ "      \"uuid\": \"string\",\n" + "      \"map-t-outside\": 0,\n" + "      \"outside\": 0\n" + "    },\n"
			+ "    \"traffic-distribution-mode\": \"string\",\n" + "    \"trunk-group-list\": [\n" + "      {\n"
			+ "        \"uuid\": \"string\",\n" + "        \"trunk-number\": 0,\n"
			+ "        \"user-tag\": \"string\",\n" + "        \"udld-timeout-cfg\": {\n" + "          \"slow\": 0,\n"
			+ "          \"fast\": 0\n" + "        },\n" + "        \"mode\": \"string\",\n"
			+ "        \"timeout\": \"string\",\n" + "        \"type\": \"string\",\n" + "        \"admin-key\": 0,\n"
			+ "        \"port-priority\": 0\n" + "      }\n" + "    ],\n" + "    \"nptv6\": {\n"
			+ "      \"domain-list\": [\n" + "        {\n" + "          \"domain-name\": \"string\",\n"
			+ "          \"bind-type\": \"string\",\n" + "          \"uuid\": \"string\"\n" + "        }\n"
			+ "      ]\n" + "    },\n" + "    \"cpu-process-dir\": \"string\",\n" + "    \"isis\": {\n"
			+ "      \"priority-list\": [\n" + "        {\n" + "          \"priority\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"padding\": 0,\n"
			+ "      \"hello-interval-minimal-list\": [\n" + "        {\n"
			+ "          \"hello-interval-minimal\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"mesh-group\": {\n" + "        \"value\": 0,\n" + "        \"blocked\": 0\n"
			+ "      },\n" + "      \"network\": \"string\",\n" + "      \"authentication\": {\n"
			+ "        \"send-only-list\": [\n" + "          {\n" + "            \"send-only\": 0,\n"
			+ "            \"level\": \"string\"\n" + "          }\n" + "        ],\n" + "        \"mode-list\": [\n"
			+ "          {\n" + "            \"mode\": \"string\",\n" + "            \"level\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"key-chain-list\": [\n" + "          {\n"
			+ "            \"key-chain\": \"string\",\n" + "            \"level\": \"string\"\n" + "          }\n"
			+ "        ]\n" + "      },\n" + "      \"csnp-interval-list\": [\n" + "        {\n"
			+ "          \"csnp-interval\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n" + "      ],\n"
			+ "      \"retransmit-interval\": 0,\n" + "      \"password-list\": [\n" + "        {\n"
			+ "          \"password\": \"string\",\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"bfd-cfg\": {\n" + "        \"disable\": 0,\n" + "        \"bfd\": 0\n"
			+ "      },\n" + "      \"wide-metric-list\": [\n" + "        {\n" + "          \"wide-metric\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"hello-interval-list\": [\n"
			+ "        {\n" + "          \"hello-interval\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"circuit-type\": \"string\",\n" + "      \"hello-multiplier-list\": [\n"
			+ "        {\n" + "          \"hello-multiplier\": 0,\n" + "          \"level\": \"string\"\n"
			+ "        }\n" + "      ],\n" + "      \"metric-list\": [\n" + "        {\n" + "          \"metric\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"lsp-interval\": 0,\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"name\": \"string\",\n"
			+ "    \"duplexity\": \"string\",\n" + "    \"icmpv6-rate-limit\": {\n" + "      \"lockup-period-v6\": 0,\n"
			+ "      \"normal-v6\": 0,\n" + "      \"lockup-v6\": 0\n" + "    },\n" + "    \"user-tag\": \"string\",\n"
			+ "    \"mtu\": 0,\n" + "    \"ipv6\": {\n" + "      \"uuid\": \"string\",\n"
			+ "      \"address-list\": [\n" + "        {\n" + "          \"address-type\": \"string\",\n"
			+ "          \"ipv6-addr\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"inside\": 0,\n"
			+ "      \"ipv6-enable\": 0,\n" + "      \"rip\": {\n" + "        \"split-horizon-cfg\": {\n"
			+ "          \"state\": \"string\"\n" + "        },\n" + "        \"uuid\": \"string\"\n" + "      },\n"
			+ "      \"outside\": 0,\n" + "      \"stateful-firewall\": {\n" + "        \"uuid\": \"string\",\n"
			+ "        \"class-list\": \"string\",\n" + "        \"acl-name\": \"string\",\n"
			+ "        \"inside\": 0,\n" + "        \"outside\": 0,\n" + "        \"access-list\": 0\n" + "      },\n"
			+ "      \"ttl-ignore\": 0,\n" + "      \"router\": {\n" + "        \"ripng\": {\n"
			+ "          \"uuid\": \"string\",\n" + "          \"rip\": 0\n" + "        },\n" + "        \"ospf\": {\n"
			+ "          \"area-list\": [\n" + "            {\n" + "              \"area-id-addr\": \"string\",\n"
			+ "              \"tag\": \"string\",\n" + "              \"instance-id\": 0,\n"
			+ "              \"area-id-num\": 0\n" + "            }\n" + "          ],\n"
			+ "          \"uuid\": \"string\"\n" + "        },\n" + "        \"isis\": {\n"
			+ "          \"tag\": \"string\",\n" + "          \"uuid\": \"string\"\n" + "        }\n" + "      },\n"
			+ "      \"access-list-cfg\": {\n" + "        \"inbound\": 0,\n" + "        \"v6-acl-name\": \"string\"\n"
			+ "      },\n" + "      \"ospf\": {\n" + "        \"uuid\": \"string\",\n" + "        \"bfd\": 0,\n"
			+ "        \"cost-cfg\": [\n" + "          {\n" + "            \"cost\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"priority-cfg\": [\n"
			+ "          {\n" + "            \"priority\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"hello-interval-cfg\": [\n" + "          {\n"
			+ "            \"hello-interval\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"mtu-ignore-cfg\": [\n" + "          {\n" + "            \"mtu-ignore\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"retransmit-interval-cfg\": [\n" + "          {\n" + "            \"retransmit-interval\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"disable\": 0,\n"
			+ "        \"transmit-delay-cfg\": [\n" + "          {\n" + "            \"transmit-delay\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"neighbor-cfg\": [\n"
			+ "          {\n" + "            \"neighbor-priority\": 0,\n" + "            \"neig-inst\": 0,\n"
			+ "            \"neighbor-poll-interval\": 0,\n" + "            \"neighbor-cost\": 0,\n"
			+ "            \"neighbor\": \"string\"\n" + "          }\n" + "        ],\n"
			+ "        \"network-list\": [\n" + "          {\n" + "            \"broadcast-type\": \"string\",\n"
			+ "            \"p2mp-nbma\": 0,\n" + "            \"network-instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"dead-interval-cfg\": [\n" + "          {\n"
			+ "            \"dead-interval\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ]\n" + "      },\n" + "      \"router-adver\": {\n" + "        \"max-interval\": 0,\n"
			+ "        \"default-lifetime\": 0,\n" + "        \"reachable-time\": 0,\n"
			+ "        \"other-config-action\": \"string\",\n" + "        \"floating-ip-default-vrid\": \"string\",\n"
			+ "        \"managed-config-action\": \"string\",\n" + "        \"min-interval\": 0,\n"
			+ "        \"rate-limit\": 0,\n" + "        \"adver-mtu-disable\": 0,\n" + "        \"prefix-list\": [\n"
			+ "          {\n" + "            \"not-autonomous\": 0,\n" + "            \"valid-lifetime\": 0,\n"
			+ "            \"not-on-link\": 0,\n" + "            \"prefix\": \"string\",\n"
			+ "            \"preferred-lifetime\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"floating-ip\": \"string\",\n" + "        \"adver-vrid\": 0,\n"
			+ "        \"use-floating-ip-default-vrid\": 0,\n" + "        \"action\": \"string\",\n"
			+ "        \"adver-vrid-default\": 0,\n" + "        \"adver-mtu\": 0,\n"
			+ "        \"retransmit-timer\": 0,\n" + "        \"hop-limit\": 0,\n" + "        \"use-floating-ip\": 0\n"
			+ "      }\n" + "    },\n" + "    \"sampling-enable\": [\n" + "      {\n"
			+ "        \"counters1\": \"string\"\n" + "      }\n" + "    ],\n" + "    \"load-interval\": 0,\n"
			+ "    \"lw-4o6\": {\n" + "      \"outside\": 0,\n" + "      \"inside\": 0,\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"action\": \"string\",\n"
			+ "    \"fec-forced-off\": 0,\n" + "    \"icmp-rate-limit\": {\n" + "      \"lockup\": 0,\n"
			+ "      \"lockup-period\": 0,\n" + "      \"normal\": 0\n" + "    },\n" + "    \"flow-control\": 0\n"
			+ "  }\n" + "}";

	public static final String ETHERNET_LIST = "{\n" + "  \"ethernet-list\": [\n" + "    {\n"
			+ "      \"fec-forced-on\": 0,\n" + "      \"trap-source\": 0,\n" + "      \"ip\": {\n"
			+ "        \"uuid\": \"string\",\n" + "        \"address-list\": [\n" + "          {\n"
			+ "            \"address-type\": \"string\",\n" + "            \"ipv6-addr\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"generate-membership-query\": 0,\n"
			+ "        \"cache-spoofing-port\": 0,\n" + "        \"inside\": 0,\n"
			+ "        \"allow-promiscuous-vip\": 0,\n" + "        \"client\": 0,\n" + "        \"max-resp-time\": 0,\n"
			+ "        \"query-interval\": 0,\n" + "        \"outside\": 0,\n" + "        \"helper-address-list\": [\n"
			+ "          {\n" + "            \"helper-address\": \"string\"\n" + "          }\n" + "        ],\n"
			+ "        \"stateful-firewall\": {\n" + "          \"uuid\": \"string\",\n"
			+ "          \"class-list\": \"string\",\n" + "          \"inside\": 0,\n" + "          \"outside\": 0,\n"
			+ "          \"acl-id\": 0,\n" + "          \"access-list\": 0\n" + "        },\n" + "        \"rip\": {\n"
			+ "          \"receive-cfg\": {\n" + "            \"receive\": 0,\n"
			+ "            \"version\": \"string\"\n" + "          },\n" + "          \"uuid\": \"string\",\n"
			+ "          \"receive-packet\": 0,\n" + "          \"split-horizon-cfg\": {\n"
			+ "            \"state\": \"string\"\n" + "          },\n" + "          \"authentication\": {\n"
			+ "            \"key-chain\": {\n" + "              \"key-chain\": \"string\"\n" + "            },\n"
			+ "            \"mode\": {\n" + "              \"mode\": \"string\"\n" + "            },\n"
			+ "            \"str\": {\n" + "              \"string\": \"string\"\n" + "            }\n"
			+ "          },\n" + "          \"send-cfg\": {\n" + "            \"version\": \"string\",\n"
			+ "            \"send\": 0\n" + "          },\n" + "          \"send-packet\": 0\n" + "        },\n"
			+ "        \"ttl-ignore\": 0,\n" + "        \"router\": {\n" + "          \"isis\": {\n"
			+ "            \"tag\": \"string\",\n" + "            \"uuid\": \"string\"\n" + "          }\n"
			+ "        },\n" + "        \"dhcp\": 0,\n" + "        \"server\": 0,\n" + "        \"ospf\": {\n"
			+ "          \"ospf-ip-list\": [\n" + "            {\n" + "              \"dead-interval\": 0,\n"
			+ "              \"authentication-key\": \"string\",\n" + "              \"uuid\": \"string\",\n"
			+ "              \"mtu-ignore\": 0,\n" + "              \"transmit-delay\": 0,\n"
			+ "              \"value\": \"string\",\n" + "              \"priority\": 0,\n"
			+ "              \"authentication\": 0,\n" + "              \"cost\": 0,\n"
			+ "              \"database-filter\": \"string\",\n" + "              \"hello-interval\": 0,\n"
			+ "              \"ip-addr\": \"string\",\n" + "              \"retransmit-interval\": 0,\n"
			+ "              \"message-digest-cfg\": [\n" + "                {\n"
			+ "                  \"message-digest-key\": 0,\n" + "                  \"md5\": {\n"
			+ "                    \"md5-value\": \"string\",\n"
			+ "                    \"encrypted\": \"Unknown Type: encrypted\"\n" + "                  }\n"
			+ "                }\n" + "              ],\n" + "              \"out\": 0\n" + "            }\n"
			+ "          ],\n" + "          \"ospf-global\": {\n" + "            \"cost\": 0,\n"
			+ "            \"dead-interval\": 0,\n" + "            \"authentication-key\": \"string\",\n"
			+ "            \"network\": {\n" + "              \"broadcast\": 0,\n"
			+ "              \"point-to-multipoint\": 0,\n" + "              \"non-broadcast\": 0,\n"
			+ "              \"point-to-point\": 0,\n" + "              \"p2mp-nbma\": 0\n" + "            },\n"
			+ "            \"mtu-ignore\": 0,\n" + "            \"transmit-delay\": 0,\n"
			+ "            \"authentication-cfg\": {\n" + "              \"authentication\": 0,\n"
			+ "              \"value\": \"string\"\n" + "            },\n" + "            \"retransmit-interval\": 0,\n"
			+ "            \"bfd-cfg\": {\n" + "              \"disable\": 0,\n" + "              \"bfd\": 0\n"
			+ "            },\n" + "            \"disable\": \"string\",\n" + "            \"hello-interval\": 0,\n"
			+ "            \"database-filter-cfg\": {\n" + "              \"database-filter\": \"string\",\n"
			+ "              \"out\": 0\n" + "            },\n" + "            \"priority\": 0,\n"
			+ "            \"mtu\": 0,\n" + "            \"message-digest-cfg\": [\n" + "              {\n"
			+ "                \"message-digest-key\": 0,\n" + "                \"md5\": {\n"
			+ "                  \"md5-value\": \"string\",\n"
			+ "                  \"encrypted\": \"Unknown Type: encrypted\"\n" + "                }\n"
			+ "              }\n" + "            ],\n" + "            \"uuid\": \"string\"\n" + "          }\n"
			+ "        },\n" + "        \"slb-partition-redirect\": 0\n" + "      },\n" + "      \"ddos\": {\n"
			+ "        \"outside\": 0,\n" + "        \"inside\": 0,\n" + "        \"uuid\": \"string\"\n" + "      },\n"
			+ "      \"l3-vlan-fwd-disable\": 0,\n" + "      \"access-list\": {\n"
			+ "        \"acl-name\": \"string\",\n" + "        \"acl-id\": 0\n" + "      },\n"
			+ "      \"speed\": \"string\",\n" + "      \"speed-forced-40g\": 0,\n" + "      \"lldp\": {\n"
			+ "        \"tx-dot1-cfg\": {\n" + "          \"link-aggregation\": 0,\n" + "          \"vlan\": 0,\n"
			+ "          \"tx-dot1-tlvs\": 0\n" + "        },\n" + "        \"notification-cfg\": {\n"
			+ "          \"notification\": 0,\n" + "          \"notif-enable\": 0\n" + "        },\n"
			+ "        \"enable-cfg\": {\n" + "          \"rx\": 0,\n" + "          \"tx\": 0,\n"
			+ "          \"rt-enable\": 0\n" + "        },\n" + "        \"tx-tlvs-cfg\": {\n"
			+ "          \"system-capabilities\": 0,\n" + "          \"system-description\": 0,\n"
			+ "          \"management-address\": 0,\n" + "          \"tx-tlvs\": 0,\n" + "          \"exclude\": 0,\n"
			+ "          \"port-description\": 0,\n" + "          \"system-name\": 0\n" + "        },\n"
			+ "        \"uuid\": \"string\"\n" + "      },\n" + "      \"uuid\": \"string\",\n" + "      \"bfd\": {\n"
			+ "        \"interval-cfg\": {\n" + "          \"interval\": 0,\n" + "          \"min-rx\": 0,\n"
			+ "          \"multiplier\": 0\n" + "        },\n" + "        \"authentication\": {\n"
			+ "          \"encrypted\": \"Unknown Type: encrypted\",\n" + "          \"password\": \"string\",\n"
			+ "          \"method\": \"string\",\n" + "          \"key-id\": 0\n" + "        },\n"
			+ "        \"echo\": 0,\n" + "        \"uuid\": \"string\",\n" + "        \"demand\": 0\n" + "      },\n"
			+ "      \"media-type-copper\": 0,\n" + "      \"ifnum\": 0,\n" + "      \"remove-vlan-tag\": 0,\n"
			+ "      \"monitor-list\": [\n" + "        {\n" + "          \"monitor-vlan\": 0,\n"
			+ "          \"monitor\": \"string\",\n" + "          \"mirror-index\": 0\n" + "        }\n" + "      ],\n"
			+ "      \"cpu-process\": 0,\n" + "      \"auto-neg-enable\": 0,\n" + "      \"map\": {\n"
			+ "        \"inside\": 0,\n" + "        \"map-t-inside\": 0,\n" + "        \"uuid\": \"string\",\n"
			+ "        \"map-t-outside\": 0,\n" + "        \"outside\": 0\n" + "      },\n"
			+ "      \"traffic-distribution-mode\": \"string\",\n" + "      \"trunk-group-list\": [\n" + "        {\n"
			+ "          \"uuid\": \"string\",\n" + "          \"trunk-number\": 0,\n"
			+ "          \"user-tag\": \"string\",\n" + "          \"udld-timeout-cfg\": {\n"
			+ "            \"slow\": 0,\n" + "            \"fast\": 0\n" + "          },\n"
			+ "          \"mode\": \"string\",\n" + "          \"timeout\": \"string\",\n"
			+ "          \"type\": \"string\",\n" + "          \"admin-key\": 0,\n" + "          \"port-priority\": 0\n"
			+ "        }\n" + "      ],\n" + "      \"nptv6\": {\n" + "        \"domain-list\": [\n" + "          {\n"
			+ "            \"domain-name\": \"string\",\n" + "            \"bind-type\": \"string\",\n"
			+ "            \"uuid\": \"string\"\n" + "          }\n" + "        ]\n" + "      },\n"
			+ "      \"cpu-process-dir\": \"string\",\n" + "      \"isis\": {\n" + "        \"priority-list\": [\n"
			+ "          {\n" + "            \"priority\": 0,\n" + "            \"level\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"padding\": 0,\n"
			+ "        \"hello-interval-minimal-list\": [\n" + "          {\n"
			+ "            \"hello-interval-minimal\": 0,\n" + "            \"level\": \"string\"\n" + "          }\n"
			+ "        ],\n" + "        \"mesh-group\": {\n" + "          \"value\": 0,\n"
			+ "          \"blocked\": 0\n" + "        },\n" + "        \"network\": \"string\",\n"
			+ "        \"authentication\": {\n" + "          \"send-only-list\": [\n" + "            {\n"
			+ "              \"send-only\": 0,\n" + "              \"level\": \"string\"\n" + "            }\n"
			+ "          ],\n" + "          \"mode-list\": [\n" + "            {\n"
			+ "              \"mode\": \"string\",\n" + "              \"level\": \"string\"\n" + "            }\n"
			+ "          ],\n" + "          \"key-chain-list\": [\n" + "            {\n"
			+ "              \"key-chain\": \"string\",\n" + "              \"level\": \"string\"\n" + "            }\n"
			+ "          ]\n" + "        },\n" + "        \"csnp-interval-list\": [\n" + "          {\n"
			+ "            \"csnp-interval\": 0,\n" + "            \"level\": \"string\"\n" + "          }\n"
			+ "        ],\n" + "        \"retransmit-interval\": 0,\n" + "        \"password-list\": [\n"
			+ "          {\n" + "            \"password\": \"string\",\n" + "            \"level\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"bfd-cfg\": {\n" + "          \"disable\": 0,\n"
			+ "          \"bfd\": 0\n" + "        },\n" + "        \"wide-metric-list\": [\n" + "          {\n"
			+ "            \"wide-metric\": 0,\n" + "            \"level\": \"string\"\n" + "          }\n"
			+ "        ],\n" + "        \"hello-interval-list\": [\n" + "          {\n"
			+ "            \"hello-interval\": 0,\n" + "            \"level\": \"string\"\n" + "          }\n"
			+ "        ],\n" + "        \"circuit-type\": \"string\",\n" + "        \"hello-multiplier-list\": [\n"
			+ "          {\n" + "            \"hello-multiplier\": 0,\n" + "            \"level\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"metric-list\": [\n" + "          {\n"
			+ "            \"metric\": 0,\n" + "            \"level\": \"string\"\n" + "          }\n" + "        ],\n"
			+ "        \"lsp-interval\": 0,\n" + "        \"uuid\": \"string\"\n" + "      },\n"
			+ "      \"name\": \"string\",\n" + "      \"duplexity\": \"string\",\n"
			+ "      \"icmpv6-rate-limit\": {\n" + "        \"lockup-period-v6\": 0,\n" + "        \"normal-v6\": 0,\n"
			+ "        \"lockup-v6\": 0\n" + "      },\n" + "      \"user-tag\": \"string\",\n" + "      \"mtu\": 0,\n"
			+ "      \"ipv6\": {\n" + "        \"uuid\": \"string\",\n" + "        \"address-list\": [\n"
			+ "          {\n" + "            \"address-type\": \"string\",\n"
			+ "            \"ipv6-addr\": \"string\"\n" + "          }\n" + "        ],\n" + "        \"inside\": 0,\n"
			+ "        \"ipv6-enable\": 0,\n" + "        \"rip\": {\n" + "          \"split-horizon-cfg\": {\n"
			+ "            \"state\": \"string\"\n" + "          },\n" + "          \"uuid\": \"string\"\n"
			+ "        },\n" + "        \"outside\": 0,\n" + "        \"stateful-firewall\": {\n"
			+ "          \"uuid\": \"string\",\n" + "          \"class-list\": \"string\",\n"
			+ "          \"acl-name\": \"string\",\n" + "          \"inside\": 0,\n" + "          \"outside\": 0,\n"
			+ "          \"access-list\": 0\n" + "        },\n" + "        \"ttl-ignore\": 0,\n"
			+ "        \"router\": {\n" + "          \"ripng\": {\n" + "            \"uuid\": \"string\",\n"
			+ "            \"rip\": 0\n" + "          },\n" + "          \"ospf\": {\n"
			+ "            \"area-list\": [\n" + "              {\n" + "                \"area-id-addr\": \"string\",\n"
			+ "                \"tag\": \"string\",\n" + "                \"instance-id\": 0,\n"
			+ "                \"area-id-num\": 0\n" + "              }\n" + "            ],\n"
			+ "            \"uuid\": \"string\"\n" + "          },\n" + "          \"isis\": {\n"
			+ "            \"tag\": \"string\",\n" + "            \"uuid\": \"string\"\n" + "          }\n"
			+ "        },\n" + "        \"access-list-cfg\": {\n" + "          \"inbound\": 0,\n"
			+ "          \"v6-acl-name\": \"string\"\n" + "        },\n" + "        \"ospf\": {\n"
			+ "          \"uuid\": \"string\",\n" + "          \"bfd\": 0,\n" + "          \"cost-cfg\": [\n"
			+ "            {\n" + "              \"cost\": 0,\n" + "              \"instance-id\": 0\n"
			+ "            }\n" + "          ],\n" + "          \"priority-cfg\": [\n" + "            {\n"
			+ "              \"priority\": 0,\n" + "              \"instance-id\": 0\n" + "            }\n"
			+ "          ],\n" + "          \"hello-interval-cfg\": [\n" + "            {\n"
			+ "              \"hello-interval\": 0,\n" + "              \"instance-id\": 0\n" + "            }\n"
			+ "          ],\n" + "          \"mtu-ignore-cfg\": [\n" + "            {\n"
			+ "              \"mtu-ignore\": 0,\n" + "              \"instance-id\": 0\n" + "            }\n"
			+ "          ],\n" + "          \"retransmit-interval-cfg\": [\n" + "            {\n"
			+ "              \"retransmit-interval\": 0,\n" + "              \"instance-id\": 0\n" + "            }\n"
			+ "          ],\n" + "          \"disable\": 0,\n" + "          \"transmit-delay-cfg\": [\n"
			+ "            {\n" + "              \"transmit-delay\": 0,\n" + "              \"instance-id\": 0\n"
			+ "            }\n" + "          ],\n" + "          \"neighbor-cfg\": [\n" + "            {\n"
			+ "              \"neighbor-priority\": 0,\n" + "              \"neig-inst\": 0,\n"
			+ "              \"neighbor-poll-interval\": 0,\n" + "              \"neighbor-cost\": 0,\n"
			+ "              \"neighbor\": \"string\"\n" + "            }\n" + "          ],\n"
			+ "          \"network-list\": [\n" + "            {\n" + "              \"broadcast-type\": \"string\",\n"
			+ "              \"p2mp-nbma\": 0,\n" + "              \"network-instance-id\": 0\n" + "            }\n"
			+ "          ],\n" + "          \"dead-interval-cfg\": [\n" + "            {\n"
			+ "              \"dead-interval\": 0,\n" + "              \"instance-id\": 0\n" + "            }\n"
			+ "          ]\n" + "        },\n" + "        \"router-adver\": {\n" + "          \"max-interval\": 0,\n"
			+ "          \"default-lifetime\": 0,\n" + "          \"reachable-time\": 0,\n"
			+ "          \"other-config-action\": \"string\",\n"
			+ "          \"floating-ip-default-vrid\": \"string\",\n"
			+ "          \"managed-config-action\": \"string\",\n" + "          \"min-interval\": 0,\n"
			+ "          \"rate-limit\": 0,\n" + "          \"adver-mtu-disable\": 0,\n"
			+ "          \"prefix-list\": [\n" + "            {\n" + "              \"not-autonomous\": 0,\n"
			+ "              \"valid-lifetime\": 0,\n" + "              \"not-on-link\": 0,\n"
			+ "              \"prefix\": \"string\",\n" + "              \"preferred-lifetime\": 0\n"
			+ "            }\n" + "          ],\n" + "          \"floating-ip\": \"string\",\n"
			+ "          \"adver-vrid\": 0,\n" + "          \"use-floating-ip-default-vrid\": 0,\n"
			+ "          \"action\": \"string\",\n" + "          \"adver-vrid-default\": 0,\n"
			+ "          \"adver-mtu\": 0,\n" + "          \"retransmit-timer\": 0,\n" + "          \"hop-limit\": 0,\n"
			+ "          \"use-floating-ip\": 0\n" + "        }\n" + "      },\n" + "      \"sampling-enable\": [\n"
			+ "        {\n" + "          \"counters1\": \"string\"\n" + "        }\n" + "      ],\n"
			+ "      \"load-interval\": 0,\n" + "      \"lw-4o6\": {\n" + "        \"outside\": 0,\n"
			+ "        \"inside\": 0,\n" + "        \"uuid\": \"string\"\n" + "      },\n"
			+ "      \"action\": \"string\",\n" + "      \"fec-forced-off\": 0,\n" + "      \"icmp-rate-limit\": {\n"
			+ "        \"lockup\": 0,\n" + "        \"lockup-period\": 0,\n" + "        \"normal\": 0\n" + "      },\n"
			+ "      \"flow-control\": 0\n" + "    }\n" + "  ]\n" + "}\n" + "\n" + "ethernet-instance\n"
			+ "Instance of ethernet\n" + "POST\n" + "/axapi/v3/interface/ethernet/{ethernet-ifnum}\n" + "Parameters\n"
			+ "Name	Description\n" + "ethernet-ifnum *\n" + "number\n" + "(path)\n" + "	\n" + "\n"
			+ "Ethernet interface number\n" + "ethernet *\n" + "(body)\n" + "	\n" + "\n" + "    Example Value\n"
			+ "    Model\n" + "\n" + "{\n" + "  \"ethernet\": {\n" + "    \"fec-forced-on\": 0,\n"
			+ "    \"trap-source\": 0,\n" + "    \"ip\": {\n" + "      \"uuid\": \"string\",\n"
			+ "      \"address-list\": [\n" + "        {\n" + "          \"address-type\": \"string\",\n"
			+ "          \"ipv6-addr\": \"string\"\n" + "        }\n" + "      ],\n"
			+ "      \"generate-membership-query\": 0,\n" + "      \"cache-spoofing-port\": 0,\n"
			+ "      \"inside\": 0,\n" + "      \"allow-promiscuous-vip\": 0,\n" + "      \"client\": 0,\n"
			+ "      \"max-resp-time\": 0,\n" + "      \"query-interval\": 0,\n" + "      \"outside\": 0,\n"
			+ "      \"helper-address-list\": [\n" + "        {\n" + "          \"helper-address\": \"string\"\n"
			+ "        }\n" + "      ],\n" + "      \"stateful-firewall\": {\n" + "        \"uuid\": \"string\",\n"
			+ "        \"class-list\": \"string\",\n" + "        \"inside\": 0,\n" + "        \"outside\": 0,\n"
			+ "        \"acl-id\": 0,\n" + "        \"access-list\": 0\n" + "      },\n" + "      \"rip\": {\n"
			+ "        \"receive-cfg\": {\n" + "          \"receive\": 0,\n" + "          \"version\": \"string\"\n"
			+ "        },\n" + "        \"uuid\": \"string\",\n" + "        \"receive-packet\": 0,\n"
			+ "        \"split-horizon-cfg\": {\n" + "          \"state\": \"string\"\n" + "        },\n"
			+ "        \"authentication\": {\n" + "          \"key-chain\": {\n"
			+ "            \"key-chain\": \"string\"\n" + "          },\n" + "          \"mode\": {\n"
			+ "            \"mode\": \"string\"\n" + "          },\n" + "          \"str\": {\n"
			+ "            \"string\": \"string\"\n" + "          }\n" + "        },\n" + "        \"send-cfg\": {\n"
			+ "          \"version\": \"string\",\n" + "          \"send\": 0\n" + "        },\n"
			+ "        \"send-packet\": 0\n" + "      },\n" + "      \"ttl-ignore\": 0,\n" + "      \"router\": {\n"
			+ "        \"isis\": {\n" + "          \"tag\": \"string\",\n" + "          \"uuid\": \"string\"\n"
			+ "        }\n" + "      },\n" + "      \"dhcp\": 0,\n" + "      \"server\": 0,\n" + "      \"ospf\": {\n"
			+ "        \"ospf-ip-list\": [\n" + "          {\n" + "            \"dead-interval\": 0,\n"
			+ "            \"authentication-key\": \"string\",\n" + "            \"uuid\": \"string\",\n"
			+ "            \"mtu-ignore\": 0,\n" + "            \"transmit-delay\": 0,\n"
			+ "            \"value\": \"string\",\n" + "            \"priority\": 0,\n"
			+ "            \"authentication\": 0,\n" + "            \"cost\": 0,\n"
			+ "            \"database-filter\": \"string\",\n" + "            \"hello-interval\": 0,\n"
			+ "            \"ip-addr\": \"string\",\n" + "            \"retransmit-interval\": 0,\n"
			+ "            \"message-digest-cfg\": [\n" + "              {\n"
			+ "                \"message-digest-key\": 0,\n" + "                \"md5\": {\n"
			+ "                  \"md5-value\": \"string\",\n"
			+ "                  \"encrypted\": \"Unknown Type: encrypted\"\n" + "                }\n"
			+ "              }\n" + "            ],\n" + "            \"out\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"ospf-global\": {\n" + "          \"cost\": 0,\n" + "          \"dead-interval\": 0,\n"
			+ "          \"authentication-key\": \"string\",\n" + "          \"network\": {\n"
			+ "            \"broadcast\": 0,\n" + "            \"point-to-multipoint\": 0,\n"
			+ "            \"non-broadcast\": 0,\n" + "            \"point-to-point\": 0,\n"
			+ "            \"p2mp-nbma\": 0\n" + "          },\n" + "          \"mtu-ignore\": 0,\n"
			+ "          \"transmit-delay\": 0,\n" + "          \"authentication-cfg\": {\n"
			+ "            \"authentication\": 0,\n" + "            \"value\": \"string\"\n" + "          },\n"
			+ "          \"retransmit-interval\": 0,\n" + "          \"bfd-cfg\": {\n" + "            \"disable\": 0,\n"
			+ "            \"bfd\": 0\n" + "          },\n" + "          \"disable\": \"string\",\n"
			+ "          \"hello-interval\": 0,\n" + "          \"database-filter-cfg\": {\n"
			+ "            \"database-filter\": \"string\",\n" + "            \"out\": 0\n" + "          },\n"
			+ "          \"priority\": 0,\n" + "          \"mtu\": 0,\n" + "          \"message-digest-cfg\": [\n"
			+ "            {\n" + "              \"message-digest-key\": 0,\n" + "              \"md5\": {\n"
			+ "                \"md5-value\": \"string\",\n"
			+ "                \"encrypted\": \"Unknown Type: encrypted\"\n" + "              }\n" + "            }\n"
			+ "          ],\n" + "          \"uuid\": \"string\"\n" + "        }\n" + "      },\n"
			+ "      \"slb-partition-redirect\": 0\n" + "    },\n" + "    \"ddos\": {\n" + "      \"outside\": 0,\n"
			+ "      \"inside\": 0,\n" + "      \"uuid\": \"string\"\n" + "    },\n"
			+ "    \"l3-vlan-fwd-disable\": 0,\n" + "    \"access-list\": {\n" + "      \"acl-name\": \"string\",\n"
			+ "      \"acl-id\": 0\n" + "    },\n" + "    \"speed\": \"string\",\n" + "    \"speed-forced-40g\": 0,\n"
			+ "    \"lldp\": {\n" + "      \"tx-dot1-cfg\": {\n" + "        \"link-aggregation\": 0,\n"
			+ "        \"vlan\": 0,\n" + "        \"tx-dot1-tlvs\": 0\n" + "      },\n"
			+ "      \"notification-cfg\": {\n" + "        \"notification\": 0,\n" + "        \"notif-enable\": 0\n"
			+ "      },\n" + "      \"enable-cfg\": {\n" + "        \"rx\": 0,\n" + "        \"tx\": 0,\n"
			+ "        \"rt-enable\": 0\n" + "      },\n" + "      \"tx-tlvs-cfg\": {\n"
			+ "        \"system-capabilities\": 0,\n" + "        \"system-description\": 0,\n"
			+ "        \"management-address\": 0,\n" + "        \"tx-tlvs\": 0,\n" + "        \"exclude\": 0,\n"
			+ "        \"port-description\": 0,\n" + "        \"system-name\": 0\n" + "      },\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"uuid\": \"string\",\n" + "    \"bfd\": {\n"
			+ "      \"interval-cfg\": {\n" + "        \"interval\": 0,\n" + "        \"min-rx\": 0,\n"
			+ "        \"multiplier\": 0\n" + "      },\n" + "      \"authentication\": {\n"
			+ "        \"encrypted\": \"Unknown Type: encrypted\",\n" + "        \"password\": \"string\",\n"
			+ "        \"method\": \"string\",\n" + "        \"key-id\": 0\n" + "      },\n" + "      \"echo\": 0,\n"
			+ "      \"uuid\": \"string\",\n" + "      \"demand\": 0\n" + "    },\n" + "    \"media-type-copper\": 0,\n"
			+ "    \"ifnum\": 0,\n" + "    \"remove-vlan-tag\": 0,\n" + "    \"monitor-list\": [\n" + "      {\n"
			+ "        \"monitor-vlan\": 0,\n" + "        \"monitor\": \"string\",\n" + "        \"mirror-index\": 0\n"
			+ "      }\n" + "    ],\n" + "    \"cpu-process\": 0,\n" + "    \"auto-neg-enable\": 0,\n"
			+ "    \"map\": {\n" + "      \"inside\": 0,\n" + "      \"map-t-inside\": 0,\n"
			+ "      \"uuid\": \"string\",\n" + "      \"map-t-outside\": 0,\n" + "      \"outside\": 0\n" + "    },\n"
			+ "    \"traffic-distribution-mode\": \"string\",\n" + "    \"trunk-group-list\": [\n" + "      {\n"
			+ "        \"uuid\": \"string\",\n" + "        \"trunk-number\": 0,\n"
			+ "        \"user-tag\": \"string\",\n" + "        \"udld-timeout-cfg\": {\n" + "          \"slow\": 0,\n"
			+ "          \"fast\": 0\n" + "        },\n" + "        \"mode\": \"string\",\n"
			+ "        \"timeout\": \"string\",\n" + "        \"type\": \"string\",\n" + "        \"admin-key\": 0,\n"
			+ "        \"port-priority\": 0\n" + "      }\n" + "    ],\n" + "    \"nptv6\": {\n"
			+ "      \"domain-list\": [\n" + "        {\n" + "          \"domain-name\": \"string\",\n"
			+ "          \"bind-type\": \"string\",\n" + "          \"uuid\": \"string\"\n" + "        }\n"
			+ "      ]\n" + "    },\n" + "    \"cpu-process-dir\": \"string\",\n" + "    \"isis\": {\n"
			+ "      \"priority-list\": [\n" + "        {\n" + "          \"priority\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"padding\": 0,\n"
			+ "      \"hello-interval-minimal-list\": [\n" + "        {\n"
			+ "          \"hello-interval-minimal\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"mesh-group\": {\n" + "        \"value\": 0,\n" + "        \"blocked\": 0\n"
			+ "      },\n" + "      \"network\": \"string\",\n" + "      \"authentication\": {\n"
			+ "        \"send-only-list\": [\n" + "          {\n" + "            \"send-only\": 0,\n"
			+ "            \"level\": \"string\"\n" + "          }\n" + "        ],\n" + "        \"mode-list\": [\n"
			+ "          {\n" + "            \"mode\": \"string\",\n" + "            \"level\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"key-chain-list\": [\n" + "          {\n"
			+ "            \"key-chain\": \"string\",\n" + "            \"level\": \"string\"\n" + "          }\n"
			+ "        ]\n" + "      },\n" + "      \"csnp-interval-list\": [\n" + "        {\n"
			+ "          \"csnp-interval\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n" + "      ],\n"
			+ "      \"retransmit-interval\": 0,\n" + "      \"password-list\": [\n" + "        {\n"
			+ "          \"password\": \"string\",\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"bfd-cfg\": {\n" + "        \"disable\": 0,\n" + "        \"bfd\": 0\n"
			+ "      },\n" + "      \"wide-metric-list\": [\n" + "        {\n" + "          \"wide-metric\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"hello-interval-list\": [\n"
			+ "        {\n" + "          \"hello-interval\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"circuit-type\": \"string\",\n" + "      \"hello-multiplier-list\": [\n"
			+ "        {\n" + "          \"hello-multiplier\": 0,\n" + "          \"level\": \"string\"\n"
			+ "        }\n" + "      ],\n" + "      \"metric-list\": [\n" + "        {\n" + "          \"metric\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"lsp-interval\": 0,\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"name\": \"string\",\n"
			+ "    \"duplexity\": \"string\",\n" + "    \"icmpv6-rate-limit\": {\n" + "      \"lockup-period-v6\": 0,\n"
			+ "      \"normal-v6\": 0,\n" + "      \"lockup-v6\": 0\n" + "    },\n" + "    \"user-tag\": \"string\",\n"
			+ "    \"mtu\": 0,\n" + "    \"ipv6\": {\n" + "      \"uuid\": \"string\",\n"
			+ "      \"address-list\": [\n" + "        {\n" + "          \"address-type\": \"string\",\n"
			+ "          \"ipv6-addr\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"inside\": 0,\n"
			+ "      \"ipv6-enable\": 0,\n" + "      \"rip\": {\n" + "        \"split-horizon-cfg\": {\n"
			+ "          \"state\": \"string\"\n" + "        },\n" + "        \"uuid\": \"string\"\n" + "      },\n"
			+ "      \"outside\": 0,\n" + "      \"stateful-firewall\": {\n" + "        \"uuid\": \"string\",\n"
			+ "        \"class-list\": \"string\",\n" + "        \"acl-name\": \"string\",\n"
			+ "        \"inside\": 0,\n" + "        \"outside\": 0,\n" + "        \"access-list\": 0\n" + "      },\n"
			+ "      \"ttl-ignore\": 0,\n" + "      \"router\": {\n" + "        \"ripng\": {\n"
			+ "          \"uuid\": \"string\",\n" + "          \"rip\": 0\n" + "        },\n" + "        \"ospf\": {\n"
			+ "          \"area-list\": [\n" + "            {\n" + "              \"area-id-addr\": \"string\",\n"
			+ "              \"tag\": \"string\",\n" + "              \"instance-id\": 0,\n"
			+ "              \"area-id-num\": 0\n" + "            }\n" + "          ],\n"
			+ "          \"uuid\": \"string\"\n" + "        },\n" + "        \"isis\": {\n"
			+ "          \"tag\": \"string\",\n" + "          \"uuid\": \"string\"\n" + "        }\n" + "      },\n"
			+ "      \"access-list-cfg\": {\n" + "        \"inbound\": 0,\n" + "        \"v6-acl-name\": \"string\"\n"
			+ "      },\n" + "      \"ospf\": {\n" + "        \"uuid\": \"string\",\n" + "        \"bfd\": 0,\n"
			+ "        \"cost-cfg\": [\n" + "          {\n" + "            \"cost\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"priority-cfg\": [\n"
			+ "          {\n" + "            \"priority\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"hello-interval-cfg\": [\n" + "          {\n"
			+ "            \"hello-interval\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"mtu-ignore-cfg\": [\n" + "          {\n" + "            \"mtu-ignore\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"retransmit-interval-cfg\": [\n" + "          {\n" + "            \"retransmit-interval\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"disable\": 0,\n"
			+ "        \"transmit-delay-cfg\": [\n" + "          {\n" + "            \"transmit-delay\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"neighbor-cfg\": [\n"
			+ "          {\n" + "            \"neighbor-priority\": 0,\n" + "            \"neig-inst\": 0,\n"
			+ "            \"neighbor-poll-interval\": 0,\n" + "            \"neighbor-cost\": 0,\n"
			+ "            \"neighbor\": \"string\"\n" + "          }\n" + "        ],\n"
			+ "        \"network-list\": [\n" + "          {\n" + "            \"broadcast-type\": \"string\",\n"
			+ "            \"p2mp-nbma\": 0,\n" + "            \"network-instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"dead-interval-cfg\": [\n" + "          {\n"
			+ "            \"dead-interval\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ]\n" + "      },\n" + "      \"router-adver\": {\n" + "        \"max-interval\": 0,\n"
			+ "        \"default-lifetime\": 0,\n" + "        \"reachable-time\": 0,\n"
			+ "        \"other-config-action\": \"string\",\n" + "        \"floating-ip-default-vrid\": \"string\",\n"
			+ "        \"managed-config-action\": \"string\",\n" + "        \"min-interval\": 0,\n"
			+ "        \"rate-limit\": 0,\n" + "        \"adver-mtu-disable\": 0,\n" + "        \"prefix-list\": [\n"
			+ "          {\n" + "            \"not-autonomous\": 0,\n" + "            \"valid-lifetime\": 0,\n"
			+ "            \"not-on-link\": 0,\n" + "            \"prefix\": \"string\",\n"
			+ "            \"preferred-lifetime\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"floating-ip\": \"string\",\n" + "        \"adver-vrid\": 0,\n"
			+ "        \"use-floating-ip-default-vrid\": 0,\n" + "        \"action\": \"string\",\n"
			+ "        \"adver-vrid-default\": 0,\n" + "        \"adver-mtu\": 0,\n"
			+ "        \"retransmit-timer\": 0,\n" + "        \"hop-limit\": 0,\n" + "        \"use-floating-ip\": 0\n"
			+ "      }\n" + "    },\n" + "    \"sampling-enable\": [\n" + "      {\n"
			+ "        \"counters1\": \"string\"\n" + "      }\n" + "    ],\n" + "    \"load-interval\": 0,\n"
			+ "    \"lw-4o6\": {\n" + "      \"outside\": 0,\n" + "      \"inside\": 0,\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"action\": \"string\",\n"
			+ "    \"fec-forced-off\": 0,\n" + "    \"icmp-rate-limit\": {\n" + "      \"lockup\": 0,\n"
			+ "      \"lockup-period\": 0,\n" + "      \"normal\": 0\n" + "    },\n" + "    \"flow-control\": 0\n"
			+ "  }\n" + "}\n" + "\n" + "Parameter content type\n" + "Responses\n" + "Response content type\n"
			+ "Code	Description\n" + "200	\n" + "\n" + "Successful api call\n" + "\n" + "    Example Value\n"
			+ "    Model\n" + "\n" + "{\n" + "  \"ethernet\": {\n" + "    \"fec-forced-on\": 0,\n"
			+ "    \"trap-source\": 0,\n" + "    \"ip\": {\n" + "      \"uuid\": \"string\",\n"
			+ "      \"address-list\": [\n" + "        {\n" + "          \"address-type\": \"string\",\n"
			+ "          \"ipv6-addr\": \"string\"\n" + "        }\n" + "      ],\n"
			+ "      \"generate-membership-query\": 0,\n" + "      \"cache-spoofing-port\": 0,\n"
			+ "      \"inside\": 0,\n" + "      \"allow-promiscuous-vip\": 0,\n" + "      \"client\": 0,\n"
			+ "      \"max-resp-time\": 0,\n" + "      \"query-interval\": 0,\n" + "      \"outside\": 0,\n"
			+ "      \"helper-address-list\": [\n" + "        {\n" + "          \"helper-address\": \"string\"\n"
			+ "        }\n" + "      ],\n" + "      \"stateful-firewall\": {\n" + "        \"uuid\": \"string\",\n"
			+ "        \"class-list\": \"string\",\n" + "        \"inside\": 0,\n" + "        \"outside\": 0,\n"
			+ "        \"acl-id\": 0,\n" + "        \"access-list\": 0\n" + "      },\n" + "      \"rip\": {\n"
			+ "        \"receive-cfg\": {\n" + "          \"receive\": 0,\n" + "          \"version\": \"string\"\n"
			+ "        },\n" + "        \"uuid\": \"string\",\n" + "        \"receive-packet\": 0,\n"
			+ "        \"split-horizon-cfg\": {\n" + "          \"state\": \"string\"\n" + "        },\n"
			+ "        \"authentication\": {\n" + "          \"key-chain\": {\n"
			+ "            \"key-chain\": \"string\"\n" + "          },\n" + "          \"mode\": {\n"
			+ "            \"mode\": \"string\"\n" + "          },\n" + "          \"str\": {\n"
			+ "            \"string\": \"string\"\n" + "          }\n" + "        },\n" + "        \"send-cfg\": {\n"
			+ "          \"version\": \"string\",\n" + "          \"send\": 0\n" + "        },\n"
			+ "        \"send-packet\": 0\n" + "      },\n" + "      \"ttl-ignore\": 0,\n" + "      \"router\": {\n"
			+ "        \"isis\": {\n" + "          \"tag\": \"string\",\n" + "          \"uuid\": \"string\"\n"
			+ "        }\n" + "      },\n" + "      \"dhcp\": 0,\n" + "      \"server\": 0,\n" + "      \"ospf\": {\n"
			+ "        \"ospf-ip-list\": [\n" + "          {\n" + "            \"dead-interval\": 0,\n"
			+ "            \"authentication-key\": \"string\",\n" + "            \"uuid\": \"string\",\n"
			+ "            \"mtu-ignore\": 0,\n" + "            \"transmit-delay\": 0,\n"
			+ "            \"value\": \"string\",\n" + "            \"priority\": 0,\n"
			+ "            \"authentication\": 0,\n" + "            \"cost\": 0,\n"
			+ "            \"database-filter\": \"string\",\n" + "            \"hello-interval\": 0,\n"
			+ "            \"ip-addr\": \"string\",\n" + "            \"retransmit-interval\": 0,\n"
			+ "            \"message-digest-cfg\": [\n" + "              {\n"
			+ "                \"message-digest-key\": 0,\n" + "                \"md5\": {\n"
			+ "                  \"md5-value\": \"string\",\n"
			+ "                  \"encrypted\": \"Unknown Type: encrypted\"\n" + "                }\n"
			+ "              }\n" + "            ],\n" + "            \"out\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"ospf-global\": {\n" + "          \"cost\": 0,\n" + "          \"dead-interval\": 0,\n"
			+ "          \"authentication-key\": \"string\",\n" + "          \"network\": {\n"
			+ "            \"broadcast\": 0,\n" + "            \"point-to-multipoint\": 0,\n"
			+ "            \"non-broadcast\": 0,\n" + "            \"point-to-point\": 0,\n"
			+ "            \"p2mp-nbma\": 0\n" + "          },\n" + "          \"mtu-ignore\": 0,\n"
			+ "          \"transmit-delay\": 0,\n" + "          \"authentication-cfg\": {\n"
			+ "            \"authentication\": 0,\n" + "            \"value\": \"string\"\n" + "          },\n"
			+ "          \"retransmit-interval\": 0,\n" + "          \"bfd-cfg\": {\n" + "            \"disable\": 0,\n"
			+ "            \"bfd\": 0\n" + "          },\n" + "          \"disable\": \"string\",\n"
			+ "          \"hello-interval\": 0,\n" + "          \"database-filter-cfg\": {\n"
			+ "            \"database-filter\": \"string\",\n" + "            \"out\": 0\n" + "          },\n"
			+ "          \"priority\": 0,\n" + "          \"mtu\": 0,\n" + "          \"message-digest-cfg\": [\n"
			+ "            {\n" + "              \"message-digest-key\": 0,\n" + "              \"md5\": {\n"
			+ "                \"md5-value\": \"string\",\n"
			+ "                \"encrypted\": \"Unknown Type: encrypted\"\n" + "              }\n" + "            }\n"
			+ "          ],\n" + "          \"uuid\": \"string\"\n" + "        }\n" + "      },\n"
			+ "      \"slb-partition-redirect\": 0\n" + "    },\n" + "    \"ddos\": {\n" + "      \"outside\": 0,\n"
			+ "      \"inside\": 0,\n" + "      \"uuid\": \"string\"\n" + "    },\n"
			+ "    \"l3-vlan-fwd-disable\": 0,\n" + "    \"access-list\": {\n" + "      \"acl-name\": \"string\",\n"
			+ "      \"acl-id\": 0\n" + "    },\n" + "    \"speed\": \"string\",\n" + "    \"speed-forced-40g\": 0,\n"
			+ "    \"lldp\": {\n" + "      \"tx-dot1-cfg\": {\n" + "        \"link-aggregation\": 0,\n"
			+ "        \"vlan\": 0,\n" + "        \"tx-dot1-tlvs\": 0\n" + "      },\n"
			+ "      \"notification-cfg\": {\n" + "        \"notification\": 0,\n" + "        \"notif-enable\": 0\n"
			+ "      },\n" + "      \"enable-cfg\": {\n" + "        \"rx\": 0,\n" + "        \"tx\": 0,\n"
			+ "        \"rt-enable\": 0\n" + "      },\n" + "      \"tx-tlvs-cfg\": {\n"
			+ "        \"system-capabilities\": 0,\n" + "        \"system-description\": 0,\n"
			+ "        \"management-address\": 0,\n" + "        \"tx-tlvs\": 0,\n" + "        \"exclude\": 0,\n"
			+ "        \"port-description\": 0,\n" + "        \"system-name\": 0\n" + "      },\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"uuid\": \"string\",\n" + "    \"bfd\": {\n"
			+ "      \"interval-cfg\": {\n" + "        \"interval\": 0,\n" + "        \"min-rx\": 0,\n"
			+ "        \"multiplier\": 0\n" + "      },\n" + "      \"authentication\": {\n"
			+ "        \"encrypted\": \"Unknown Type: encrypted\",\n" + "        \"password\": \"string\",\n"
			+ "        \"method\": \"string\",\n" + "        \"key-id\": 0\n" + "      },\n" + "      \"echo\": 0,\n"
			+ "      \"uuid\": \"string\",\n" + "      \"demand\": 0\n" + "    },\n" + "    \"media-type-copper\": 0,\n"
			+ "    \"ifnum\": 0,\n" + "    \"remove-vlan-tag\": 0,\n" + "    \"monitor-list\": [\n" + "      {\n"
			+ "        \"monitor-vlan\": 0,\n" + "        \"monitor\": \"string\",\n" + "        \"mirror-index\": 0\n"
			+ "      }\n" + "    ],\n" + "    \"cpu-process\": 0,\n" + "    \"auto-neg-enable\": 0,\n"
			+ "    \"map\": {\n" + "      \"inside\": 0,\n" + "      \"map-t-inside\": 0,\n"
			+ "      \"uuid\": \"string\",\n" + "      \"map-t-outside\": 0,\n" + "      \"outside\": 0\n" + "    },\n"
			+ "    \"traffic-distribution-mode\": \"string\",\n" + "    \"trunk-group-list\": [\n" + "      {\n"
			+ "        \"uuid\": \"string\",\n" + "        \"trunk-number\": 0,\n"
			+ "        \"user-tag\": \"string\",\n" + "        \"udld-timeout-cfg\": {\n" + "          \"slow\": 0,\n"
			+ "          \"fast\": 0\n" + "        },\n" + "        \"mode\": \"string\",\n"
			+ "        \"timeout\": \"string\",\n" + "        \"type\": \"string\",\n" + "        \"admin-key\": 0,\n"
			+ "        \"port-priority\": 0\n" + "      }\n" + "    ],\n" + "    \"nptv6\": {\n"
			+ "      \"domain-list\": [\n" + "        {\n" + "          \"domain-name\": \"string\",\n"
			+ "          \"bind-type\": \"string\",\n" + "          \"uuid\": \"string\"\n" + "        }\n"
			+ "      ]\n" + "    },\n" + "    \"cpu-process-dir\": \"string\",\n" + "    \"isis\": {\n"
			+ "      \"priority-list\": [\n" + "        {\n" + "          \"priority\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"padding\": 0,\n"
			+ "      \"hello-interval-minimal-list\": [\n" + "        {\n"
			+ "          \"hello-interval-minimal\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"mesh-group\": {\n" + "        \"value\": 0,\n" + "        \"blocked\": 0\n"
			+ "      },\n" + "      \"network\": \"string\",\n" + "      \"authentication\": {\n"
			+ "        \"send-only-list\": [\n" + "          {\n" + "            \"send-only\": 0,\n"
			+ "            \"level\": \"string\"\n" + "          }\n" + "        ],\n" + "        \"mode-list\": [\n"
			+ "          {\n" + "            \"mode\": \"string\",\n" + "            \"level\": \"string\"\n"
			+ "          }\n" + "        ],\n" + "        \"key-chain-list\": [\n" + "          {\n"
			+ "            \"key-chain\": \"string\",\n" + "            \"level\": \"string\"\n" + "          }\n"
			+ "        ]\n" + "      },\n" + "      \"csnp-interval-list\": [\n" + "        {\n"
			+ "          \"csnp-interval\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n" + "      ],\n"
			+ "      \"retransmit-interval\": 0,\n" + "      \"password-list\": [\n" + "        {\n"
			+ "          \"password\": \"string\",\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"bfd-cfg\": {\n" + "        \"disable\": 0,\n" + "        \"bfd\": 0\n"
			+ "      },\n" + "      \"wide-metric-list\": [\n" + "        {\n" + "          \"wide-metric\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"hello-interval-list\": [\n"
			+ "        {\n" + "          \"hello-interval\": 0,\n" + "          \"level\": \"string\"\n" + "        }\n"
			+ "      ],\n" + "      \"circuit-type\": \"string\",\n" + "      \"hello-multiplier-list\": [\n"
			+ "        {\n" + "          \"hello-multiplier\": 0,\n" + "          \"level\": \"string\"\n"
			+ "        }\n" + "      ],\n" + "      \"metric-list\": [\n" + "        {\n" + "          \"metric\": 0,\n"
			+ "          \"level\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"lsp-interval\": 0,\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"name\": \"string\",\n"
			+ "    \"duplexity\": \"string\",\n" + "    \"icmpv6-rate-limit\": {\n" + "      \"lockup-period-v6\": 0,\n"
			+ "      \"normal-v6\": 0,\n" + "      \"lockup-v6\": 0\n" + "    },\n" + "    \"user-tag\": \"string\",\n"
			+ "    \"mtu\": 0,\n" + "    \"ipv6\": {\n" + "      \"uuid\": \"string\",\n"
			+ "      \"address-list\": [\n" + "        {\n" + "          \"address-type\": \"string\",\n"
			+ "          \"ipv6-addr\": \"string\"\n" + "        }\n" + "      ],\n" + "      \"inside\": 0,\n"
			+ "      \"ipv6-enable\": 0,\n" + "      \"rip\": {\n" + "        \"split-horizon-cfg\": {\n"
			+ "          \"state\": \"string\"\n" + "        },\n" + "        \"uuid\": \"string\"\n" + "      },\n"
			+ "      \"outside\": 0,\n" + "      \"stateful-firewall\": {\n" + "        \"uuid\": \"string\",\n"
			+ "        \"class-list\": \"string\",\n" + "        \"acl-name\": \"string\",\n"
			+ "        \"inside\": 0,\n" + "        \"outside\": 0,\n" + "        \"access-list\": 0\n" + "      },\n"
			+ "      \"ttl-ignore\": 0,\n" + "      \"router\": {\n" + "        \"ripng\": {\n"
			+ "          \"uuid\": \"string\",\n" + "          \"rip\": 0\n" + "        },\n" + "        \"ospf\": {\n"
			+ "          \"area-list\": [\n" + "            {\n" + "              \"area-id-addr\": \"string\",\n"
			+ "              \"tag\": \"string\",\n" + "              \"instance-id\": 0,\n"
			+ "              \"area-id-num\": 0\n" + "            }\n" + "          ],\n"
			+ "          \"uuid\": \"string\"\n" + "        },\n" + "        \"isis\": {\n"
			+ "          \"tag\": \"string\",\n" + "          \"uuid\": \"string\"\n" + "        }\n" + "      },\n"
			+ "      \"access-list-cfg\": {\n" + "        \"inbound\": 0,\n" + "        \"v6-acl-name\": \"string\"\n"
			+ "      },\n" + "      \"ospf\": {\n" + "        \"uuid\": \"string\",\n" + "        \"bfd\": 0,\n"
			+ "        \"cost-cfg\": [\n" + "          {\n" + "            \"cost\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"priority-cfg\": [\n"
			+ "          {\n" + "            \"priority\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"hello-interval-cfg\": [\n" + "          {\n"
			+ "            \"hello-interval\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"mtu-ignore-cfg\": [\n" + "          {\n" + "            \"mtu-ignore\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"retransmit-interval-cfg\": [\n" + "          {\n" + "            \"retransmit-interval\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"disable\": 0,\n"
			+ "        \"transmit-delay-cfg\": [\n" + "          {\n" + "            \"transmit-delay\": 0,\n"
			+ "            \"instance-id\": 0\n" + "          }\n" + "        ],\n" + "        \"neighbor-cfg\": [\n"
			+ "          {\n" + "            \"neighbor-priority\": 0,\n" + "            \"neig-inst\": 0,\n"
			+ "            \"neighbor-poll-interval\": 0,\n" + "            \"neighbor-cost\": 0,\n"
			+ "            \"neighbor\": \"string\"\n" + "          }\n" + "        ],\n"
			+ "        \"network-list\": [\n" + "          {\n" + "            \"broadcast-type\": \"string\",\n"
			+ "            \"p2mp-nbma\": 0,\n" + "            \"network-instance-id\": 0\n" + "          }\n"
			+ "        ],\n" + "        \"dead-interval-cfg\": [\n" + "          {\n"
			+ "            \"dead-interval\": 0,\n" + "            \"instance-id\": 0\n" + "          }\n"
			+ "        ]\n" + "      },\n" + "      \"router-adver\": {\n" + "        \"max-interval\": 0,\n"
			+ "        \"default-lifetime\": 0,\n" + "        \"reachable-time\": 0,\n"
			+ "        \"other-config-action\": \"string\",\n" + "        \"floating-ip-default-vrid\": \"string\",\n"
			+ "        \"managed-config-action\": \"string\",\n" + "        \"min-interval\": 0,\n"
			+ "        \"rate-limit\": 0,\n" + "        \"adver-mtu-disable\": 0,\n" + "        \"prefix-list\": [\n"
			+ "          {\n" + "            \"not-autonomous\": 0,\n" + "            \"valid-lifetime\": 0,\n"
			+ "            \"not-on-link\": 0,\n" + "            \"prefix\": \"string\",\n"
			+ "            \"preferred-lifetime\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"floating-ip\": \"string\",\n" + "        \"adver-vrid\": 0,\n"
			+ "        \"use-floating-ip-default-vrid\": 0,\n" + "        \"action\": \"string\",\n"
			+ "        \"adver-vrid-default\": 0,\n" + "        \"adver-mtu\": 0,\n"
			+ "        \"retransmit-timer\": 0,\n" + "        \"hop-limit\": 0,\n" + "        \"use-floating-ip\": 0\n"
			+ "      }\n" + "    },\n" + "    \"sampling-enable\": [\n" + "      {\n"
			+ "        \"counters1\": \"string\"\n" + "      }\n" + "    ],\n" + "    \"load-interval\": 0,\n"
			+ "    \"lw-4o6\": {\n" + "      \"outside\": 0,\n" + "      \"inside\": 0,\n"
			+ "      \"uuid\": \"string\"\n" + "    },\n" + "    \"action\": \"string\",\n"
			+ "    \"fec-forced-off\": 0,\n" + "    \"icmp-rate-limit\": {\n" + "      \"lockup\": 0,\n"
			+ "      \"lockup-period\": 0,\n" + "      \"normal\": 0\n" + "    },\n" + "    \"flow-control\": 0\n"
			+ "  }\n" + "}";

	public static final String OP_ETH = "{\n" + "  \"ethernet\": {\n" + "    \"ifnum\":1,\n"
			+ "    \"l3-vlan-fwd-disable\":0,\n" + "    \"load-interval\":300,\n" + "    \"mtu\":1500,\n"
			+ "    \"trap-source\":0,\n" + "    \"duplexity\":\"auto\",\n" + "    \"speed\":\"auto\",\n"
			+ "    \"flow-control\":0,\n" + "    \"action\":\"disable\",\n"
			+ "    \"uuid\":\"1a1e71ec-a948-11e9-9f90-0233e17c8e2a\"\n" + "  }\n" + "}";

	public static final String RIB_ROUTE = "{\n" + "  \"rib\": {\n" + "    \"ip-nexthop-lif\": [\n" + "      {\n"
			+ "        \"description-nexthop-lif\": \"string\",\n" + "        \"lif\": 0\n" + "      }\n" + "    ],\n"
			+ "    \"ip-nexthop-ipv4\": [\n" + "      {\n" + "        \"description-nexthop-ip\": \"string\",\n"
			+ "        \"ip-next-hop\": \"string\",\n" + "        \"distance-nexthop-ip\": 0\n" + "      }\n"
			+ "    ],\n" + "    \"uuid\": \"string\",\n" + "    \"ip-dest-addr\": \"string\",\n"
			+ "    \"ip-nexthop-tunnel\": [\n" + "      {\n" + "        \"tunnel\": 0,\n"
			+ "        \"ip-next-hop-tunnel\": \"string\",\n" + "        \"distance-nexthop-tunnel\": 0,\n"
			+ "        \"description-nexthop-tunnel\": \"string\"\n" + "      }\n" + "    ],\n"
			+ "    \"ip-nexthop-partition\": [\n" + "      {\n" + "        \"partition-name\": \"string\",\n"
			+ "        \"vrid-num-in-partition\": 0,\n" + "        \"description-nexthop-partition\": \"string\",\n"
			+ "        \"description-partition-vrid\": \"string\"\n" + "      }\n" + "    ],\n"
			+ "    \"ip-mask\": \"string\"\n" + "  }\n" + "}";

	public static final String VRRP_COMMON = "{\n" + "  \"common\": {\n" + "    \"forward-l4-packet-on-standby\": 0,\n"
			+ "    \"get-ready-time\": 0,\n" + "    \"hello-interval\": 0,\n" + "    \"uuid\": \"string\",\n"
			+ "    \"preemption-delay\": 0,\n" + "    \"set-id\": 0,\n" + "    \"device-id\": 0,\n"
			+ "    \"arp-retry\": 0,\n" + "    \"dead-timer\": 0,\n" + "    \"disable-default-vrid\": 0,\n"
			+ "    \"track-event-delay\": 0,\n" + "    \"action\": \"string\",\n" + "    \"hostid-append-to-vrid\": {\n"
			+ "      \"hostid-append-to-vrid-value\": 0,\n" + "      \"hostid-append-to-vrid-default\": 0\n"
			+ "    },\n" + "    \"restart-time\": 0,\n" + "    \"inline-mode-cfg\": {\n" + "      \"inline-mode\": 0,\n"
			+ "      \"preferred-trunk\": 0,\n" + "      \"preferred-port\": 0\n" + "    }\n" + "  }\n" + "}";

	public static final String VRRP_VRID = "{\n" + "  \"vrid\": {\n" + "    \"blade-parameters\": {\n"
			+ "      \"priority\": 0,\n" + "      \"fail-over-policy-template\": \"string\",\n"
			+ "      \"uuid\": \"string\",\n" + "      \"tracking-options\": {\n" + "        \"vlan-cfg\": [\n"
			+ "          {\n" + "            \"vlan\": 0,\n" + "            \"timeout\": 0,\n"
			+ "            \"priority-cost\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"uuid\": \"string\",\n" + "        \"route\": {\n" + "          \"ipv6-destination-cfg\": [\n"
			+ "            {\n" + "              \"distance\": 0,\n" + "              \"protocol\": \"string\",\n"
			+ "              \"priority-cost\": 0,\n" + "              \"ipv6-destination\": \"string\",\n"
			+ "              \"gatewayv6\": \"string\"\n" + "            }\n" + "          ],\n"
			+ "          \"ip-destination-cfg\": [\n" + "            {\n" + "              \"distance\": 0,\n"
			+ "              \"protocol\": \"string\",\n" + "              \"mask\": \"string\",\n"
			+ "              \"priority-cost\": 0,\n" + "              \"ip-destination\": \"string\",\n"
			+ "              \"gateway\": \"string\"\n" + "            }\n" + "          ]\n" + "        },\n"
			+ "        \"bgp\": {\n" + "          \"bgp-ipv4-address-cfg\": [\n" + "            {\n"
			+ "              \"bgp-ipv4-address\": \"string\",\n" + "              \"priority-cost\": 0\n"
			+ "            }\n" + "          ],\n" + "          \"bgp-ipv6-address-cfg\": [\n" + "            {\n"
			+ "              \"bgp-ipv6-address\": \"string\",\n" + "              \"priority-cost\": 0\n"
			+ "            }\n" + "          ]\n" + "        },\n" + "        \"interface\": [\n" + "          {\n"
			+ "            \"ethernet\": 0,\n" + "            \"priority-cost\": 0\n" + "          }\n" + "        ],\n"
			+ "        \"gateway\": {\n" + "          \"ipv4-gateway-list\": [\n" + "            {\n"
			+ "              \"uuid\": \"string\",\n" + "              \"ip-address\": \"string\",\n"
			+ "              \"priority-cost\": 0\n" + "            }\n" + "          ],\n"
			+ "          \"ipv6-gateway-list\": [\n" + "            {\n"
			+ "              \"ipv6-address\": \"string\",\n" + "              \"uuid\": \"string\",\n"
			+ "              \"priority-cost\": 0\n" + "            }\n" + "          ]\n" + "        },\n"
			+ "        \"trunk-cfg\": [\n" + "          {\n" + "            \"priority-cost\": 0,\n"
			+ "            \"trunk\": 0,\n" + "            \"per-port-pri\": 0\n" + "          }\n" + "        ]\n"
			+ "      }\n" + "    },\n" + "    \"uuid\": \"string\",\n" + "    \"vrid-val\": 0,\n"
			+ "    \"user-tag\": \"string\",\n" + "    \"preempt-mode\": {\n" + "      \"threshold\": 0,\n"
			+ "      \"disable\": 0\n" + "    },\n" + "    \"floating-ip\": {\n"
			+ "      \"ipv6-address-part-cfg\": [\n" + "        {\n" + "          \"ethernet\": 0,\n"
			+ "          \"ipv6-address-partition\": \"string\",\n" + "          \"ve\": 0,\n"
			+ "          \"trunk\": 0\n" + "        }\n" + "      ],\n" + "      \"ip-address-cfg\": [\n"
			+ "        {\n" + "          \"ip-address\": \"string\"\n" + "        }\n" + "      ],\n"
			+ "      \"ip-address-part-cfg\": [\n" + "        {\n" + "          \"ip-address-partition\": \"string\"\n"
			+ "        }\n" + "      ],\n" + "      \"ipv6-address-cfg\": [\n" + "        {\n"
			+ "          \"ipv6-address\": \"string\",\n" + "          \"ethernet\": 0,\n" + "          \"ve\": 0,\n"
			+ "          \"trunk\": 0\n" + "        }\n" + "      ]\n" + "    },\n" + "    \"follow\": {\n"
			+ "      \"vrid-lead\": \"string\"\n" + "    }\n" + "  }\n" + "}";

	public static final String VRRP_PEER_GROUP = "{\n" + "  \"peer-group\": {\n" + "    \"peer\": {\n"
			+ "      \"ip-peer-address-cfg\": [\n" + "        {\n" + "          \"ip-peer-address\": \"string\"\n"
			+ "        }\n" + "      ],\n" + "      \"ipv6-peer-address-cfg\": [\n" + "        {\n"
			+ "          \"ipv6-peer-address\": \"string\"\n" + "        }\n" + "      ]\n" + "    },\n"
			+ "    \"uuid\": \"string\"\n" + "  }\n" + "}";

	public static final String IMPORT = "{\n" + "  \"import\": {\n" + "    \"geo-location\": \"string\",\n"
			+ "    \"ssl-cert-key\": \"string\",\n" + "    \"class-list-convert\": \"string\",\n"
			+ "    \"bw-list\": \"string\",\n" + "    \"usb-license\": \"string\",\n"
			+ "    \"ip-map-list\": \"string\",\n" + "    \"health-external\": {\n"
			+ "      \"description\": \"string\",\n" + "      \"remote-file\": \"string\",\n"
			+ "      \"externalfilename\": \"string\",\n" + "      \"password\": \"string\",\n"
			+ "      \"use-mgmt-port\": 0,\n" + "      \"overwrite\": 0\n" + "    },\n"
			+ "    \"auth-portal\": \"string\",\n" + "    \"local-uri-file\": \"string\",\n"
			+ "    \"aflex\": \"string\",\n" + "    \"overwrite\": 0,\n" + "    \"class-list-type\": \"string\",\n"
			+ "    \"pfx-password\": \"string\",\n" + "    \"web-category-license\": \"string\",\n"
			+ "    \"thales-kmdata\": \"string\",\n" + "    \"secured\": 0,\n" + "    \"ssl-crl\": \"string\",\n"
			+ "    \"terminal\": 0,\n" + "    \"policy\": \"string\",\n"
			+ "    \"file-inspection-bw-list\": \"string\",\n" + "    \"thales-secworld\": \"string\",\n"
			+ "    \"lw-4o6\": \"string\",\n" + "    \"auth-portal-image\": \"string\",\n"
			+ "    \"health-postfile\": {\n" + "      \"postfilename\": \"string\",\n"
			+ "      \"password\": \"string\",\n" + "      \"use-mgmt-port\": 0,\n"
			+ "      \"remote-file\": \"string\",\n" + "      \"overwrite\": 0\n" + "    },\n"
			+ "    \"class-list\": \"string\",\n" + "    \"glm-license\": \"string\",\n"
			+ "    \"dnssec-ds\": \"string\",\n" + "    \"cloud-creds\": \"string\",\n"
			+ "    \"auth-jwks\": \"string\",\n" + "    \"wsdl\": \"string\",\n" + "    \"password\": \"string\",\n"
			+ "    \"ssl-key\": \"string\",\n" + "    \"use-mgmt-port\": 0,\n" + "    \"remote-file\": \"string\",\n"
			+ "    \"cloud-config\": \"string\",\n" + "    \"to-device\": {\n"
			+ "      \"web-category-license\": \"string\",\n" + "      \"remote-file\": \"string\",\n"
			+ "      \"glm-license\": \"string\",\n" + "      \"glm-cert\": \"string\",\n" + "      \"device\": 0,\n"
			+ "      \"use-mgmt-port\": 0,\n" + "      \"overwrite\": 0\n" + "    },\n"
			+ "    \"user-tag\": \"string\",\n" + "    \"store-name\": \"string\",\n" + "    \"ca-cert\": \"string\",\n"
			+ "    \"glm-cert\": \"string\",\n" + "    \"store\": {\n" + "      \"create\": 0,\n"
			+ "      \"name\": \"string\",\n" + "      \"remote-file\": \"string\",\n" + "      \"delete\": 0\n"
			+ "    },\n" + "    \"xml-schema\": \"string\",\n" + "    \"certificate-type\": \"string\",\n"
			+ "    \"auth-saml-idp\": {\n" + "      \"remote-file\": \"string\",\n"
			+ "      \"saml-idp-name\": \"string\",\n" + "      \"verify-xml-signature\": 0,\n"
			+ "      \"password\": \"string\",\n" + "      \"use-mgmt-port\": 0,\n" + "      \"overwrite\": 0\n"
			+ "    },\n" + "    \"ssl-cert\": \"string\",\n" + "    \"dnssec-dnskey\": \"string\"\n" + "  }\n" + "}";

	public static final String REBOOT = "{\n" + "  \"reboot\": {\n" + "    \"all\": 0,\n" + "    \"day-of-month\": 0,\n"
			+ "    \"reason-3\": \"string\",\n" + "    \"reason-2\": \"string\",\n" + "    \"in\": \"string\",\n"
			+ "    \"month-2\": \"string\",\n" + "    \"month\": \"string\",\n" + "    \"device\": 0,\n"
			+ "    \"reason\": \"string\",\n" + "    \"at\": 0,\n" + "    \"time\": \"string\",\n"
			+ "    \"cancel\": 0,\n" + "    \"day-of-month-2\": 0\n" + "  }\n" + "}";

	public static final String DNS_PRIMARY = "{\n" + "  \"primary\": {\n" + "    \"ip-v4-addr\": \"string\",\n"
			+ "    \"ip-v6-addr\": \"string\",\n" + "    \"uuid\": \"string\"\n" + "  }\n" + "}";

	public static final String SESSION_SYNC = "{\n" + "  \"session-sync\": {\n" + "    \"action\": \"string\",\n"
			+ "    \"uuid\": \"string\"\n" + "  }\n" + "}";

	public static final String GLM = "{\n" + "  \"glm\": {\n" + "    \"uuid\": \"string\",\n"
			+ "    \"use-mgmt-port\": 0,\n" + "    \"burst\": 0,\n" + "    \"interval\": 0,\n" + "    \"send\": {\n"
			+ "      \"license-request\": 0\n" + "    },\n" + "    \"token\": \"string\",\n"
			+ "    \"enterprise\": \"string\",\n" + "    \"proxy-server\": {\n" + "      \"username\": \"string\",\n"
			+ "      \"uuid\": \"string\",\n" + "      \"encrypted\": \"Unknown Type: encrypted\",\n"
			+ "      \"host\": \"string\",\n" + "      \"password\": 0,\n" + "      \"port\": 0,\n"
			+ "      \"secret-string\": \"string\"\n" + "    },\n" + "    \"appliance-name\": \"string\",\n"
			+ "    \"enable-requests\": 0,\n" + "    \"allocate-bandwidth\": 0,\n" + "    \"port\": 0\n" + "  }\n"
			+ "}";

	public static final String CONF_SYNC = "{\n" + "  \"sync\": {\n" + "    \"all-partitions\": 0,\n"
			+ "    \"private-key\": \"string\",\n" + "    \"partition-name\": \"string\",\n"
			+ "    \"pwd\": \"string\",\n" + "    \"auto-authentication\": 0,\n" + "    \"address\": \"string\",\n"
			+ "    \"shared\": 0,\n" + "    \"type\": \"string\",\n" + "    \"pwd-enc\": \"Unknown Type: encrypted\",\n"
			+ "    \"usr\": \"string\"\n" + "  }\n" + "}";

	public static final String HARMONY_CONTROLLER_PROFILE = "{\n" + "	  \"profile\" : {\n"
			+ "               \"host\" : \"10.43.12.108\",\n" + "                \"port\" : 8443,\n"
			+ "		\"user-name\" : \"scampbell@a10networks.com\",\n" + "		\"secret-value\" : \"admin123\",\n"
			+ "		\"provider\" : \"root\",\n" + "		\"thunder-mgmt-ip\" : {\n"
			+ "		\"ip-address\" : \"10.43.12.108\"\n" + "		},\n" + "		\"action\" : \"register\",\n"
			+ "		\"use-mgmt-port\" : 1,\n" + "		\"region\" : \"India\",\n"
			+ "		\"availability-zone\" : \"Pune\"\n" + "	  }}";

	public static final String OVERLAY_TUNNEL_OPTIONS = "{\n" + "  \"options\": {\n"
			+ "    \"nvgre-key-mode-lower24\": 0,\n" + "    \"uuid\": \"string\",\n"
			+ "    \"tcp-mss-adjust-disable\": 0,\n" + "    \"gateway-mac\": \"string\",\n"
			+ "    \"ip-dscp-preserve\": 0,\n" + "    \"nvgre-disable-flow-id\": 0,\n" + "    \"vxlan-dest-port\": 0\n"
			+ "  }\n" + "}";

	public static final String OVERLAY_TUNNEL_VTEP = "{\n" + "  \"vtep\": {\n" + "    \"uuid\": \"string\",\n"
			+ "    \"user-tag\": \"string\",\n" + "    \"sampling-enable\": [\n" + "      {\n"
			+ "        \"counters1\": \"string\"\n" + "      }\n" + "    ],\n" + "    \"source-ip-address\": {\n"
			+ "      \"ip-address\": \"string\",\n" + "      \"uuid\": \"string\",\n" + "      \"vni-list\": [\n"
			+ "        {\n" + "          \"segment\": 0,\n" + "          \"uuid\": \"string\"\n" + "        }\n"
			+ "      ]\n" + "    },\n" + "    \"encap\": \"string\",\n" + "    \"host-list\": [\n" + "      {\n"
			+ "        \"destination-vtep\": \"string\",\n" + "        \"ip-addr\": \"string\",\n"
			+ "        \"overlay-mac-addr\": \"string\",\n" + "        \"vni\": 0,\n" + "        \"uuid\": \"string\"\n"
			+ "      }\n" + "    ],\n" + "    \"id\": 0,\n" + "    \"destination-ip-address-list\": [\n" + "      {\n"
			+ "        \"uuid\": \"string\",\n" + "        \"ip-address\": \"string\",\n" + "        \"vni-list\": [\n"
			+ "          {\n" + "            \"segment\": 0,\n" + "            \"uuid\": \"string\"\n" + "          }\n"
			+ "        ],\n" + "        \"user-tag\": \"string\",\n" + "        \"encap\": \"string\"\n" + "      }\n"
			+ "    ]\n" + "  }\n" + "}";
}
